package net.hypejet.jet.protocol.packet.clientbound.login.encryption;

import net.hypejet.jet.protocol.packet.clientbound.ClientBoundPacket;
import org.checkerframework.checker.nullness.qual.NonNull;

/**
 * Represents a {@link ClientBoundPacket client-bound packet}, which requests an encryption from a Minecraft client.
 *
 * @since 1.0
 * @author Codestech
 * @see ClientBoundPacket
 */
public sealed interface EncryptionRequestPacket extends ClientBoundPacket permits EncryptionRequestPacketImpl {
    /**
     * Gets an identifier of a server requesting the encryption.
     *
     * @return the identifier
     * @since 1.0
     */
    @NonNull String serverId();

    /**
     * Gets a public key of a server requesting the encryption.
     *
     * @return the public key
     * @since 1.0
     */
    byte @NonNull [] publicKey();

    /**
     * Gets a verify token, which is a random sequence of bytes generated by a server requesting the encryption.
     *
     * @return the verify token
     * @since 1.0
     */
    byte @NonNull [] verifyToken();

    /**
     * Gets whether the client should authenticate with Mojang.
     *
     * @return true if the client should authenticate with Mojang, false otherwise
     * @since 1.0
     */
    boolean shouldAuthenticate();

    /**
     * Creates a new {@link Builder encryption request packet builder}.
     *
     * @return the encryption request packet builder
     * @since 1.0
     */
    static @NonNull Builder builder() {
        return new EncryptionRequestPacketImpl.Builder();
    }

    /**
     * Represents a builder that creates a {@link EncryptionRequestPacket encryption request packet}.
     *
     * @since 1.0
     * @author Codestech
     */
    sealed interface Builder permits EncryptionRequestPacketImpl.Builder {
        /**
         * Sets an identifier of a server requesting the encryption.
         *
         * @param serverId the identifier
         * @return the builder
         * @since 1.0
         */
        @NonNull Builder serverId(@NonNull String serverId);

        /**
         * Sets a public key of a server requesting the encryption.
         *
         * @param publicKey the public key
         * @return the builder
         * @since 1.0
         */
        @NonNull Builder publicKey(byte @NonNull [] publicKey);

        /**
         * Sets a verify token, which is a random sequence of bytes generated by a server requesting the encryption.
         *
         * @param verifyToken the verify token
         * @return the builder
         * @since 1.0
         */
        @NonNull Builder verifyToken(byte @NonNull [] verifyToken);

        /**
         * Sets whether the client should authenticate with Mojang.
         *
         * @param shouldAuthenticate true if the client should authenticate with Mojang, false otherwise
         * @return the builder
         * @since 1.0
         */
        @NonNull Builder shouldAuthenticate(boolean shouldAuthenticate);

        /**
         * Build the {@link EncryptionRequestPacket encryption request packet}.
         *
         * @return the encryption request packet
         * @since 1.0
         */
        @NonNull EncryptionRequestPacket build();
    }
}