package net.hypejet.jet.data.generator.generator.generators;

import com.google.gson.reflect.TypeToken;
import net.hypejet.jet.data.generator.extractor.RegistryExtractor;
import net.hypejet.jet.data.generator.generator.ResourceGenerator;
import net.hypejet.jet.data.json.DataJson;
import net.hypejet.jet.data.json.entry.JsonRegistryEntry;
import net.minecraft.core.RegistryAccess;
import org.jetbrains.annotations.NotNull;

import java.nio.file.Path;
import java.util.List;
import java.util.Objects;

/**
 * Represents a {@linkplain ResourceGenerator resource generator} which generates an JSON-serialized output containing
 * data extracted from a {@linkplain RegistryExtractor registry extractor}.
 *
 * @param <T> a type of values of registry entries extracted by the registry extractor
 * @since 1.0
 * @see RegistryExtractor
 * @see ResourceGenerator
 */
public final class RegistryExtractorResourceGenerator<T> implements ResourceGenerator {

    private final RegistryExtractor<T> registryExtractor;
    private final RegistryAccess registryAccess;
    private final Path path;

    /**
     * Constructs the {@linkplain RegistryExtractorResourceGenerator registry extractor resource generator}.
     *
     * @param registryExtractor a registry extractor that the generator should use for data extraction
     * @param registryAccess a registry access that should be passed as an argument to the registry extractor
     * @param path a relative path of a file that should have the output generated by the generator
     * @since 1.0
     */
    public RegistryExtractorResourceGenerator(@NotNull RegistryExtractor<T> registryExtractor,
                                              @NotNull RegistryAccess registryAccess, @NotNull Path path) {
        this.registryExtractor = Objects.requireNonNull(registryExtractor, "registry extractor");
        this.registryAccess = Objects.requireNonNull(registryAccess, "registry access");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public @NotNull String generate() {
        Class<T> valueClass = this.registryExtractor.valueClass();
        TypeToken<?> dataEntryToken = TypeToken.getParameterized(JsonRegistryEntry.class, valueClass);
        TypeToken<?> dataEntryListToken = TypeToken.getParameterized(List.class, dataEntryToken.getType());
        return DataJson.GSON.toJson(this.registryExtractor.extract(this.registryAccess), dataEntryListToken.getType());
    }

    @Override
    public @NotNull Path path() {
        return this.path;
    }
}