package net.hypejet.jet.server;

import net.hypejet.concurrency.collection.CollectionAcquisition;
import net.hypejet.concurrency.collection.set.HashSetAcquirable;
import net.hypejet.jet.MinecraftServer;
import net.hypejet.jet.data.autogenerated.server.MinecraftVersionInfo;
import net.hypejet.jet.event.events.server.ServerReadyEvent;
import net.hypejet.jet.event.events.server.ServerShutdownEvent;
import net.hypejet.jet.event.node.EventNode;
import net.hypejet.jet.server.command.JetCommandManager;
import net.hypejet.jet.server.configuration.JetServerConfiguration;
import net.hypejet.jet.server.configuration.unparsed.UnparsedServerConfiguration;
import net.hypejet.jet.server.entity.player.JetPlayer;
import net.hypejet.jet.server.network.NetworkManager;
import net.hypejet.jet.server.plugin.JetPluginManager;
import net.hypejet.jet.server.registry.JetRegistryManager;
import net.hypejet.jet.server.scoreboard.JetScoreboard;
import net.hypejet.jet.server.world.JetWorldManager;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Represents an implementation of the {@linkplain MinecraftServer Minecraft server}.
 *
 * @since 1.0
 * @see MinecraftServer
 */
public final class JetMinecraftServer implements MinecraftServer {

    private static final String BRAND_NAME = "Jet";
    private static final Logger LOGGER = LoggerFactory.getLogger(JetMinecraftServer.class);

    private final EventNode<Object> eventNode = new EventNode<>(Object.class);
    private final JetServerConfiguration configuration;

    private final NetworkManager networkManager;

    private final JetCommandManager commandManager;
    private final JetRegistryManager registryManager;
    private final JetPluginManager pluginManager;
    private final JetWorldManager worldManager;

    private final JetScoreboard scoreboard;
    private final HashSetAcquirable<JetPlayer> players = new HashSetAcquirable<>();

    /**
     * Constructs the {@linkplain JetMinecraftServer Minecraft server}.
     *
     * @since 1.0
     */
    JetMinecraftServer() {
        this.configuration = JetServerConfiguration.parse(this, UnparsedServerConfiguration.create());
        this.commandManager = new JetCommandManager(this);
        this.registryManager = new JetRegistryManager(this);
        this.worldManager = new JetWorldManager(this);
        this.scoreboard = new JetScoreboard(this);
        this.pluginManager = new JetPluginManager(this);
        this.networkManager = new NetworkManager(this);
        this.eventNode.call(new ServerReadyEvent());
    }

    @Override
    public @NonNull EventNode<Object> eventNode() {
        return this.eventNode;
    }

    @Override
    public int protocolVersion() {
        return MinecraftVersionInfo.PROTOCOL_VERSION;
    }

    @Override
    public @NonNull String minecraftVersion() {
        return MinecraftVersionInfo.VERSION_NAME;
    }

    @Override
    public @NonNull String brandName() {
        return BRAND_NAME;
    }

    @Override
    public @NonNull JetServerConfiguration configuration() {
        return this.configuration;
    }

    @Override
    public void shutdown() {
        LOGGER.info("Shutting down the server...");
        this.eventNode.addListener(new ServerShutdownEvent());
        this.networkManager.shutdown();
        this.pluginManager.shutdown();
        LOGGER.info("Successfully shut down the server");
    }

    @Override
    public @NonNull CollectionAcquisition<JetPlayer, ?> players() {
        return this.players.acquireRead();
    }

    @Override
    public @NonNull JetCommandManager commandManager() {
        return this.commandManager;
    }

    @Override
    public @NonNull JetPluginManager pluginManager() {
        return this.pluginManager;
    }

    @Override
    public @NonNull JetRegistryManager registryManager() {
        return this.registryManager;
    }

    @Override
    public @NonNull JetWorldManager worldManager() {
        return this.worldManager;
    }

    @Override
    public @NonNull JetScoreboard scoreboard() {
        return this.scoreboard;
    }

    /**
     * Registers a player on the server.
     *
     * @param player the player
     * @since 1.0
     */
    public void registerPlayer(@NonNull JetPlayer player) {
        try (CollectionAcquisition<JetPlayer, ?> acquisition = this.players.acquireWrite()) {
            /* A call outside event loop is safe in this case, when a player gets disconnected, the unregister method
               is going to be called, and that method also creates a write acquisition, so no race conditions should
               happen. */
            if (player.connection().isActive())
                acquisition.collection().add(player);
        }
    }

    /**
     * Unregisters a player from the server.
     *
     * @param player the player
     * @since 1.0
     */
    public void unregisterPlayer(@NonNull JetPlayer player) {
        try (CollectionAcquisition<JetPlayer, ?> acquisition = this.players.acquireWrite()) {
            acquisition.collection().remove(player);
        }
    }
}