package net.hypejet.jet.server.network.protocol.packet.client;

import io.netty.util.collection.IntObjectHashMap;
import io.netty.util.collection.IntObjectMap;
import net.hypejet.jet.data.autogenerated.server.ClientConfigurationPackets;
import net.hypejet.jet.data.autogenerated.server.ClientHandshakePackets;
import net.hypejet.jet.data.autogenerated.server.ClientLoginPackets;
import net.hypejet.jet.data.autogenerated.server.ClientPlayPackets;
import net.hypejet.jet.data.autogenerated.server.ClientStatusPackets;
import net.hypejet.jet.data.autogenerated.server.ResourceFileNames;
import net.hypejet.jet.data.codecs.JetDataJson;
import net.hypejet.jet.data.model.api.utils.NullabilityUtil;
import net.hypejet.jet.data.model.server.registry.registries.registry.DataRegistryEntry;
import net.hypejet.jet.protocol.ProtocolState;
import net.hypejet.jet.protocol.packet.client.ClientPacket;
import net.hypejet.jet.server.network.protocol.packet.client.handler.configuration.ClientAcknowledgeFinishConfigurationPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.configuration.ClientCookieResponseConfigurationPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.configuration.ClientInformationConfigurationPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.configuration.ClientKeepAliveConfigurationPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.configuration.ClientKnownPacksConfigurationPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.configuration.ClientPluginMessageConfigurationPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.configuration.ClientPongConfigurationPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.configuration.ClientResourcePackResponseConfigurationPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.handshake.HandshakePacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.login.ClientCookieResponseLoginPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.login.ClientEncryptionResponseLoginPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.login.ClientLoginAcknowledgeLoginPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.login.ClientLoginRequestLoginPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.login.ClientPluginMessageResponseLoginPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientAcknowledgeMessagePlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientActionPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientChangeDifficultyPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientChatCommandPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientChatSessionUpdatePlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientCommandSuggestionsRequestPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientConfirmTeleportationPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientEndTickPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientInformationPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientKeepAlivePlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientOnGroundPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientPluginMessagePlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientPositionPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientQueryBlockEntityTagPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientRequestActionPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientRotationAndPositionPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientRotationPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientSignedChatCommandPlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.play.ClientSignedChatMessagePlayPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.status.ClientPingRequestStatusPacketHandler;
import net.hypejet.jet.server.network.protocol.packet.client.handler.status.ClientServerListRequestStatusPacketHandler;
import net.hypejet.jet.server.registry.JetMinecraftRegistry;
import net.kyori.adventure.key.Key;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

import java.util.EnumMap;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Represents a registry of {@linkplain ClientPacketHandler client packet handlers}.
 *
 * @since 1.0
 * @author Codestech
 * @see ClientPacket
 * @see ClientPacketHandler
 */
public final class ClientPacketRegistry {

    private final Map<ProtocolState, ProtocolStateSpecification> specifications;

    /**
     * Constructs the {@linkplain ClientPacketRegistry client packet registry}.
     *
     * @since 1.0
     */
    public ClientPacketRegistry() {
        Map<ProtocolState, ProtocolStateSpecification> specifications = new EnumMap<>(ProtocolState.class);

        specifications.put(
                ProtocolState.HANDSHAKE,
                new ProtocolStateSpecification.Builder(ResourceFileNames.CLIENT_HANDSHAKE_PACKET_GENERATOR)
                        .add(ClientHandshakePackets.INTENTION, new HandshakePacketHandler())
                        .build()
        );

        specifications.put(
                ProtocolState.STATUS,
                new ProtocolStateSpecification.Builder(ResourceFileNames.CLIENT_STATUS_PACKET_GENERATOR)
                        .add(ClientStatusPackets.STATUS_REQUEST, new ClientServerListRequestStatusPacketHandler())
                        .add(ClientStatusPackets.PING_REQUEST, new ClientPingRequestStatusPacketHandler())
                        .build()
        );

        specifications.put(
                ProtocolState.LOGIN,
                new ProtocolStateSpecification.Builder(ResourceFileNames.CLIENT_LOGIN_PACKET_GENERATOR)
                        .add(ClientLoginPackets.HELLO, new ClientLoginRequestLoginPacketHandler())
                        .add(ClientLoginPackets.KEY, new ClientEncryptionResponseLoginPacketHandler())
                        .add(ClientLoginPackets.COOKIE_RESPONSE, new ClientCookieResponseLoginPacketHandler())
                        .add(ClientLoginPackets.LOGIN_ACKNOWLEDGED, new ClientLoginAcknowledgeLoginPacketHandler())
                        .add(ClientLoginPackets.CUSTOM_QUERY_ANSWER,
                                new ClientPluginMessageResponseLoginPacketHandler())
                        .build()
        );

        specifications.put(
                ProtocolState.CONFIGURATION,
                new ProtocolStateSpecification.Builder(ResourceFileNames.CLIENT_CONFIGURATION_PACKET_GENERATOR)
                        .add(ClientConfigurationPackets.PONG, new ClientPongConfigurationPacketHandler())
                        .add(ClientConfigurationPackets.KEEP_ALIVE, new ClientKeepAliveConfigurationPacketHandler())
                        .add(ClientConfigurationPackets.CUSTOM_PAYLOAD,
                                new ClientPluginMessageConfigurationPacketHandler())
                        .add(ClientConfigurationPackets.CLIENT_INFORMATION,
                                new ClientInformationConfigurationPacketHandler())
                        .add(ClientConfigurationPackets.COOKIE_RESPONSE,
                                new ClientCookieResponseConfigurationPacketHandler())
                        .add(ClientConfigurationPackets.RESOURCE_PACK,
                                new ClientResourcePackResponseConfigurationPacketHandler())
                        .add(ClientConfigurationPackets.FINISH_CONFIGURATION,
                                new ClientAcknowledgeFinishConfigurationPacketHandler())
                        .add(ClientConfigurationPackets.SELECT_KNOWN_PACKS,
                                new ClientKnownPacksConfigurationPacketHandler())
                        .build()
        );

        specifications.put(
                ProtocolState.PLAY,
                new ProtocolStateSpecification.Builder(ResourceFileNames.CLIENT_PLAY_PACKET_GENERATOR)
                        .add(ClientPlayPackets.KEEP_ALIVE, new ClientKeepAlivePlayPacketHandler())
                        .add(ClientPlayPackets.CUSTOM_PAYLOAD, new ClientPluginMessagePlayPacketHandler())
                        .add(ClientPlayPackets.MOVE_PLAYER_POS_ROT, new ClientRotationAndPositionPlayPacketHandler())
                        .add(ClientPlayPackets.MOVE_PLAYER_ROT, new ClientRotationPlayPacketHandler())
                        .add(ClientPlayPackets.MOVE_PLAYER_POS, new ClientPositionPlayPacketHandler())
                        .add(ClientPlayPackets.MOVE_PLAYER_STATUS_ONLY, new ClientOnGroundPlayPacketHandler())
                        .add(ClientPlayPackets.PLAYER_COMMAND, new ClientActionPlayPacketHandler())
                        .add(ClientPlayPackets.ACCEPT_TELEPORTATION, new ClientConfirmTeleportationPlayPacketHandler())
                        .add(ClientPlayPackets.BLOCK_ENTITY_TAG_QUERY, new ClientQueryBlockEntityTagPacketHandler())
                        .add(ClientPlayPackets.CHANGE_DIFFICULTY, new ClientChangeDifficultyPlayPacketHandler())
                        .add(ClientPlayPackets.CHAT_ACK, new ClientAcknowledgeMessagePlayPacketHandler())
                        .add(ClientPlayPackets.CHAT_COMMAND, new ClientChatCommandPlayPacketHandler())
                        .add(ClientPlayPackets.CHAT_COMMAND_SIGNED, new ClientSignedChatCommandPlayPacketHandler())
                        .add(ClientPlayPackets.CHAT, new ClientSignedChatMessagePlayPacketHandler())
                        .add(ClientPlayPackets.CHAT_SESSION_UPDATE, new ClientChatSessionUpdatePlayPacketHandler())
                        .add(ClientPlayPackets.CLIENT_COMMAND, new ClientRequestActionPlayPacketHandler())
                        .add(ClientPlayPackets.CLIENT_INFORMATION, new ClientInformationPlayPacketHandler())
                        .add(ClientPlayPackets.CLIENT_TICK_END, new ClientEndTickPlayPacketHandler())
                        .add(ClientPlayPackets.COMMAND_SUGGESTION,
                                new ClientCommandSuggestionsRequestPlayPacketHandler())
                        .build()
        );

        this.specifications = specifications;
    }

    /**
     * Gets {@linkplain ClientPacketHandler a client packet handler} for a packet specified, which was registered in
     * this registry.
     *
     * @param packetId an identifier of the packet
     * @param protocolState a protocol state, during which the packet is handled
     * @return the client packet handler, {@code null} if not present
     * @since 1.0
     */
    public @Nullable ClientPacketHandler<?> handlerFor(int packetId, @NonNull ProtocolState protocolState) {
        NullabilityUtil.requireNonNull(protocolState, "protocol state");
        ProtocolStateSpecification specification = this.specifications.get(protocolState);
        if (specification == null) return null;
        return specification.handlerFor(packetId);
    }

    /**
     * Represents a specification of {@linkplain ProtocolState a protocol state}, which holds all
     * {@linkplain ClientPacketHandler client packet handlers}, which handle packets during that protocol state.
     *
     * @since 1.0
     * @see ProtocolState
     * @see ClientPacketHandler
     */
    private static final class ProtocolStateSpecification {

        private final IntObjectMap<ClientPacketHandler<?>> identifierToHandlerMap;

        /**
         * Constructs the {@linkplain ProtocolStateSpecification protocol state specification}.
         *
         * @param entries a collection of entries that should be registered in the specification
         * @param specificationResourceFileName a name of a resource file containing all identifiers of the packets
         * @since 1.0
         */
        private ProtocolStateSpecification(@NonNull Set<Entry<?>> entries,
                                           @NonNull String specificationResourceFileName) {
            NullabilityUtil.requireNonNull(entries, "entries");
            NullabilityUtil.requireNonNull(specificationResourceFileName, "specification resource file name");

            List<DataRegistryEntry<?>> registryEntries = JetMinecraftRegistry.entries(
                    JetDataJson.createPacketGson(),
                    specificationResourceFileName
            );

            Map<Key, Integer> packetKeyToIdentifierMap = new HashMap<>();
            for (DataRegistryEntry<?> registryEntry : registryEntries) {
                // TODO: Replace with primitive type when it finally gets implemented in java
                if (!(registryEntry.value() instanceof Integer identifier))
                    throw new IllegalArgumentException("The value is not an integer");
                packetKeyToIdentifierMap.put(registryEntry.key(), identifier);
            }

            IntObjectMap<ClientPacketHandler<?>> identifierToHandlerMap = new IntObjectHashMap<>();
            for (Entry<?> entry : entries) {
                Key packetKey = entry.packetKey();
                Integer packetIdentifier = packetKeyToIdentifierMap.get(packetKey);

                if (packetIdentifier == null) {
                    throw new IllegalArgumentException(String.format(
                            "Could not find a packet identifier for a key of %s", packetKey
                    ));
                }

                identifierToHandlerMap.put(packetIdentifier, entry.handler());
            }

            this.identifierToHandlerMap = identifierToHandlerMap;
        }

        /**
         * Gets {@linkplain ClientPacketHandler a client packet handler} for a packet with an identifier specified.
         *
         * @param packetIdentifier the packet identifier
         * @return the client packet handler
         * @since 1.0
         */
        private @Nullable ClientPacketHandler<?> handlerFor(int packetIdentifier) {
            return this.identifierToHandlerMap.get(packetIdentifier);
        }

        /**
         * Represents a builder of {@linkplain ProtocolStateSpecification a protocol state specification}.
         *
         * @since 1.0
         * @see ProtocolStateSpecification
         */
        private static final class Builder {

            private final String specificationResourceFileName;
            private final Set<Entry<?>> entries = new HashSet<>();

            /**
             * Constructs the {@linkplain Builder builder}.
             *
             * @param specificationResourceFileName a name of a resource file containing all identifiers of the packets
             * @since 1.0
             */
            private Builder(@NonNull String specificationResourceFileName) {
                this.specificationResourceFileName = NullabilityUtil.requireNonNull(specificationResourceFileName,
                        "specification resource file name");
            }

            /**
             * Creates and adds {@linkplain Entry an entry} of the {@linkplain ProtocolStateSpecification protocol
             * state specification} to the builder.
             *
             * @param packetKey a key of the packet
             * @param handler a handler of the packet
             * @return this builder
             * @param <P> a type of the packet
             * @since 1.0
             */
            private <P extends ClientPacket> @NonNull Builder add(@NonNull Key packetKey,
                                                                  @NonNull ClientPacketHandler<P> handler) {
                NullabilityUtil.requireNonNull(packetKey, "packet key");
                NullabilityUtil.requireNonNull(handler, "handler");
                this.entries.add(new Entry<>(packetKey, handler));
                return this;
            }

            /**
             * Builds {@linkplain ProtocolStateSpecification a protocol state specification} using all data
             * specified in this builder.
             *
             * @return the packet
             * @since 1.0
             */
            private @NonNull ProtocolStateSpecification build() {
                return new ProtocolStateSpecification(Set.copyOf(this.entries), this.specificationResourceFileName);
            }
        }

        /**
         * Represents an entry of the {@linkplain ProtocolStateSpecification protocol state specification}.
         *
         * @param packetKey a key of the packet
         * @param handler a handler of the packet
         * @param <P> a type of the packet
         * @since 1.0
         */
        private record Entry<P extends ClientPacket>(@NonNull Key packetKey, @NonNull ClientPacketHandler<P> handler) {
            /**
             * Constructs the {@linkplain Entry entry}.
             *
             * @param packetKey a key of the packet
             * @param handler handler of the packet
             * @since 1.0
             */
            private Entry {
                NullabilityUtil.requireNonNull(packetKey, "packet key");
                NullabilityUtil.requireNonNull(handler, "handler");
            }
        }
    }
}