package net.hypejet.jet.server.network.packet.packets.server;

import net.hypejet.jet.data.autogenerated.server.ResourceFileNames;
import net.hypejet.jet.data.autogenerated.server.ServerConfigurationPackets;
import net.hypejet.jet.data.autogenerated.server.ServerLoginPackets;
import net.hypejet.jet.data.autogenerated.server.ServerPlayPackets;
import net.hypejet.jet.data.autogenerated.server.ServerStatusPackets;
import net.hypejet.jet.data.codecs.JetDataJson;
import net.hypejet.jet.data.model.api.utils.NullabilityUtil;
import net.hypejet.jet.data.model.server.registry.registries.registry.DataRegistryEntry;
import net.hypejet.jet.server.network.ProtocolState;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerAddResourcePackPacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerCookieRequestPacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerCustomLinksPacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerCustomReportDetailsPacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerDisconnectPacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerKeepAlivePacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerPingPacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerPluginMessagePacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerRemoveResourcePackPacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerStoreCookiePacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerTransferPacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerUpdateTagsPacket;
import net.hypejet.jet.server.network.packet.packets.server.configuration.ServerFeatureFlagsConfigurationPacket;
import net.hypejet.jet.server.network.packet.packets.server.configuration.ServerFinishConfigurationPacket;
import net.hypejet.jet.server.network.packet.packets.server.configuration.ServerKnownPacksConfigurationPacket;
import net.hypejet.jet.server.network.packet.packets.server.configuration.ServerRegistryDataConfigurationPacket;
import net.hypejet.jet.server.network.packet.packets.server.configuration.ServerResetChatConfigurationPacket;
import net.hypejet.jet.server.network.packet.packets.server.login.ServerEnableCompressionLoginPacket;
import net.hypejet.jet.server.network.packet.packets.server.login.ServerEncryptionRequestLoginPacket;
import net.hypejet.jet.server.network.packet.packets.server.login.ServerLoginSuccessLoginPacket;
import net.hypejet.jet.server.network.packet.packets.server.login.ServerPluginMessageRequestLoginPacket;
import net.hypejet.jet.server.network.packet.packets.server.play.ServerActionBarPlayPacket;
import net.hypejet.jet.server.network.packet.packets.server.play.ServerCenterChunkPlayPacket;
import net.hypejet.jet.server.network.packet.packets.server.play.ServerCommandSuggestionsResponsePlayPacket;
import net.hypejet.jet.server.network.packet.packets.server.play.ServerDeclareCommandsPlayPacket;
import net.hypejet.jet.server.network.packet.packets.server.play.ServerGameEventPlayPacket;
import net.hypejet.jet.server.network.packet.packets.server.play.ServerJoinGamePlayPacket;
import net.hypejet.jet.server.network.packet.packets.server.play.ServerPlayerListHeaderAndFooterPlayPacket;
import net.hypejet.jet.server.network.packet.packets.server.play.ServerSynchronizePositionPlayPacket;
import net.hypejet.jet.server.network.packet.packets.server.play.ServerSystemMessagePlayPacket;
import net.hypejet.jet.server.network.packet.packets.server.status.ServerListResponseStatusPacket;
import net.hypejet.jet.server.network.packet.packets.server.common.ServerPingResponsePacket;
import net.hypejet.jet.server.network.codec.NetworkWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerAddResourcePackPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerCookieRequestPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerCustomLinksPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerCustomReportDetailsPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerDisconnectPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerKeepAlivePacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerPingPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerPluginMessagePacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerRemoveResourcePackPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerStoreCookiePacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerTransferPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerUpdateTagsPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.configuration.ServerFeatureFlagsConfigurationPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.configuration.ServerKnownPacksConfigurationPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.configuration.ServerRegistryDataConfigurationPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.login.ServerDisconnectLoginPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.login.ServerEnableCompressionLoginPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.login.ServerEncryptionRequestLoginPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.login.ServerLoginSuccessLoginPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.play.ServerPlayerListHeaderAndFooterPlayPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.login.ServerPluginMessageRequestLoginPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.play.ServerActionBarPlayPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.play.ServerCenterChunkPlayPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.play.ServerCommandSuggestionsResponsePlayPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.play.ServerDeclareCommandsPlayPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.play.ServerGameEventPlayPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.play.ServerJoinGamePlayPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.play.ServerSynchronizePositionPlayPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.play.ServerSystemMessagePlayPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.status.ServerListResponseStatusPacketWriter;
import net.hypejet.jet.server.network.codec.packet.server.common.ServerPingResponsePacketWriter;
import net.hypejet.jet.server.registry.JetMinecraftRegistry;
import net.kyori.adventure.key.Key;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

import java.util.EnumMap;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Represents a registry of {@linkplain NetworkWriter network writers}, which write {@linkplain ServerPacket server
 * packets}.
 *
 * @since 1.0
 * @author Codestech
 * @see ServerPacket
 * @see NetworkWriter
 */
public final class ServerPacketRegistry {

    private static final Map<ProtocolState, ProtocolStateSpecification> SPECIFICATIONS;

    static {
        Map<ProtocolState, ProtocolStateSpecification> specifications = new EnumMap<>(ProtocolState.class);

        ServerCookieRequestPacketWriter cookieRequestWriter = new ServerCookieRequestPacketWriter();
        ServerCustomLinksPacketWriter customLinksWriter = new ServerCustomLinksPacketWriter();
        ServerDisconnectPacketWriter disconnectWriter = new ServerDisconnectPacketWriter();
        ServerKeepAlivePacketWriter keepAliveWriter = new ServerKeepAlivePacketWriter();
        ServerPingPacketWriter pingWriter = new ServerPingPacketWriter();
        ServerPluginMessagePacketWriter pluginMessageWriter = new ServerPluginMessagePacketWriter();
        ServerTransferPacketWriter transferWriter = new ServerTransferPacketWriter();
        ServerStoreCookiePacketWriter storeCookieWriter = new ServerStoreCookiePacketWriter();
        ServerUpdateTagsPacketWriter updateTagsWriter = new ServerUpdateTagsPacketWriter();
        ServerCustomReportDetailsPacketWriter customReportDetailsWriter = new ServerCustomReportDetailsPacketWriter();
        ServerAddResourcePackPacketWriter addResourcePackWriter = new ServerAddResourcePackPacketWriter();
        ServerRemoveResourcePackPacketWriter removeResourcePackWriter = new ServerRemoveResourcePackPacketWriter();
        ServerPingResponsePacketWriter pingResponseWriter = new ServerPingResponsePacketWriter();

        specifications.put(
                ProtocolState.STATUS,
                new ProtocolStateSpecification.Builder(ResourceFileNames.SERVER_STATUS_PACKET_GENERATOR)
                        .add(ServerStatusPackets.PONG_RESPONSE, ServerPingResponsePacket.class, pingResponseWriter)
                        .add(ServerStatusPackets.STATUS_RESPONSE, ServerListResponseStatusPacket.class,
                                new ServerListResponseStatusPacketWriter())
                        .build()
        );

        specifications.put(
                ProtocolState.LOGIN,
                new ProtocolStateSpecification.Builder(ResourceFileNames.SERVER_LOGIN_PACKET_GENERATOR)
                        .add(ServerLoginPackets.COOKIE_REQUEST, ServerCookieRequestPacket.class, cookieRequestWriter)
                        .add(ServerLoginPackets.LOGIN_DISCONNECT, ServerDisconnectPacket.class,
                                new ServerDisconnectLoginPacketWriter())
                        .add(ServerLoginPackets.HELLO, ServerEncryptionRequestLoginPacket.class,
                                new ServerEncryptionRequestLoginPacketWriter())
                        .add(ServerLoginPackets.LOGIN_FINISHED, ServerLoginSuccessLoginPacket.class,
                                new ServerLoginSuccessLoginPacketWriter())
                        .add(ServerLoginPackets.LOGIN_COMPRESSION, ServerEnableCompressionLoginPacket.class,
                                new ServerEnableCompressionLoginPacketWriter())
                        .add(ServerLoginPackets.CUSTOM_QUERY, ServerPluginMessageRequestLoginPacket.class,
                                new ServerPluginMessageRequestLoginPacketWriter())
                        .build()
        );

        specifications.put(
                ProtocolState.CONFIGURATION,
                new ProtocolStateSpecification.Builder(ResourceFileNames.SERVER_CONFIGURATION_PACKET_GENERATOR)
                        .add(ServerConfigurationPackets.SERVER_LINKS, ServerCustomLinksPacket.class, customLinksWriter)
                        .add(ServerConfigurationPackets.DISCONNECT, ServerDisconnectPacket.class, disconnectWriter)
                        .add(ServerConfigurationPackets.KEEP_ALIVE, ServerKeepAlivePacket.class, keepAliveWriter)
                        .add(ServerConfigurationPackets.PING, ServerPingPacket.class, pingWriter)
                        .add(ServerConfigurationPackets.TRANSFER, ServerTransferPacket.class, transferWriter)
                        .add(ServerConfigurationPackets.STORE_COOKIE, ServerStoreCookiePacket.class, storeCookieWriter)
                        .add(ServerConfigurationPackets.UPDATE_TAGS, ServerUpdateTagsPacket.class, updateTagsWriter)
                        .add(ServerConfigurationPackets.COOKIE_REQUEST, ServerCookieRequestPacket.class,
                                cookieRequestWriter)
                        .add(ServerConfigurationPackets.CUSTOM_PAYLOAD, ServerPluginMessagePacket.class,
                                pluginMessageWriter)
                        .add(ServerConfigurationPackets.CUSTOM_REPORT_DETAILS, ServerCustomReportDetailsPacket.class,
                                customReportDetailsWriter)
                        .add(ServerConfigurationPackets.RESOURCE_PACK_PUSH, ServerAddResourcePackPacket.class,
                                addResourcePackWriter)
                        .add(ServerConfigurationPackets.RESOURCE_PACK_POP, ServerRemoveResourcePackPacket.class,
                                removeResourcePackWriter)
                        .add(ServerConfigurationPackets.SELECT_KNOWN_PACKS, ServerKnownPacksConfigurationPacket.class,
                                new ServerKnownPacksConfigurationPacketWriter())
                        .add(ServerConfigurationPackets.REGISTRY_DATA, ServerRegistryDataConfigurationPacket.class,
                                new ServerRegistryDataConfigurationPacketWriter())
                        .add(ServerConfigurationPackets.UPDATE_ENABLED_FEATURES,
                                ServerFeatureFlagsConfigurationPacket.class,
                                new ServerFeatureFlagsConfigurationPacketWriter())
                        .add(ServerConfigurationPackets.FINISH_CONFIGURATION, ServerFinishConfigurationPacket.class,
                                (buf, object) -> {})
                        .add(ServerConfigurationPackets.RESET_CHAT, ServerResetChatConfigurationPacket.class,
                                (buf, object) -> {})
                        .build()
        );

        specifications.put(
                ProtocolState.PLAY,
                new ProtocolStateSpecification.Builder(ResourceFileNames.SERVER_PLAY_PACKET_GENERATOR)
                        .add(ServerPlayPackets.COOKIE_REQUEST, ServerCookieRequestPacket.class, cookieRequestWriter)
                        .add(ServerPlayPackets.KEEP_ALIVE, ServerKeepAlivePacket.class, keepAliveWriter)
                        .add(ServerPlayPackets.DISCONNECT, ServerDisconnectPacket.class, disconnectWriter)
                        .add(ServerPlayPackets.CUSTOM_PAYLOAD, ServerPluginMessagePacket.class, pluginMessageWriter)
                        .add(ServerPlayPackets.SERVER_LINKS, ServerCustomLinksPacket.class, customLinksWriter)
                        .add(ServerPlayPackets.PING, ServerPingPacket.class, pingWriter)
                        .add(ServerPlayPackets.TRANSFER, ServerTransferPacket.class, transferWriter)
                        .add(ServerPlayPackets.STORE_COOKIE, ServerStoreCookiePacket.class, storeCookieWriter)
                        .add(ServerPlayPackets.UPDATE_TAGS, ServerUpdateTagsPacket.class, updateTagsWriter)
                        .add(ServerPlayPackets.PONG_RESPONSE, ServerPingResponsePacket.class, pingResponseWriter)
                        .add(ServerPlayPackets.CUSTOM_REPORT_DETAILS, ServerCustomReportDetailsPacket.class,
                                customReportDetailsWriter)
                        .add(ServerPlayPackets.RESOURCE_PACK_PUSH, ServerAddResourcePackPacket.class,
                                addResourcePackWriter)
                        .add(ServerPlayPackets.RESOURCE_PACK_POP, ServerRemoveResourcePackPacket.class,
                                removeResourcePackWriter)
                        .add(ServerPlayPackets.LOGIN, ServerJoinGamePlayPacket.class,
                                new ServerJoinGamePlayPacketWriter())
                        .add(ServerPlayPackets.GAME_EVENT, ServerGameEventPlayPacket.class,
                                new ServerGameEventPlayPacketWriter())
                        .add(ServerPlayPackets.SYSTEM_CHAT, ServerSystemMessagePlayPacket.class,
                                new ServerSystemMessagePlayPacketWriter())
                        .add(ServerPlayPackets.SET_ACTION_BAR_TEXT, ServerActionBarPlayPacket.class,
                                new ServerActionBarPlayPacketWriter())
                        .add(ServerPlayPackets.TAB_LIST, ServerPlayerListHeaderAndFooterPlayPacket.class,
                                new ServerPlayerListHeaderAndFooterPlayPacketWriter())
                        .add(ServerPlayPackets.ENTITY_POSITION_SYNC, ServerSynchronizePositionPlayPacket.class,
                                new ServerSynchronizePositionPlayPacketWriter())
                        .add(ServerPlayPackets.SET_CHUNK_CACHE_CENTER, ServerCenterChunkPlayPacket.class,
                                new ServerCenterChunkPlayPacketWriter())
                        .add(ServerPlayPackets.COMMANDS, ServerDeclareCommandsPlayPacket.class,
                                new ServerDeclareCommandsPlayPacketWriter())
                        .add(ServerPlayPackets.COMMAND_SUGGESTIONS, ServerCommandSuggestionsResponsePlayPacket.class,
                                new ServerCommandSuggestionsResponsePlayPacketWriter())
                        .build()
        );

        SPECIFICATIONS = specifications;
    }

    private ServerPacketRegistry() {}

    /**
     * Gets whether a packet is supported in {@linkplain ProtocolState a protocol state} specified.
     *
     * @param protocolState the protocol state
     * @param packetClass a class of the packet
     * @return {@code true} if the packet is supported in the protocol state specified, {@code false} otherwise
     * @since 1.0
     */
    public static boolean isSupported(@NonNull ProtocolState protocolState,
                                      @NonNull Class<? extends ServerPacket> packetClass) {
        return specificationFor(protocolState, packetClass) != null;
    }

    /**
     * Gets {@linkplain RegistryPacketSpecification a registry packet specification} for a packet with
     * a class specified.
     *
     * @param protocolState a protocol state, during which the packet is written
     * @param packetClass a class of the packet
     * @return the registry packet specification, {@code null} if not present
     * @since 1.0
     */
    public static @Nullable RegistryPacketSpecification<? extends ServerPacket> specificationFor(
            @NonNull ProtocolState protocolState, @NonNull Class<? extends ServerPacket> packetClass
    ) {
        NullabilityUtil.requireNonNull(protocolState, "protocol state");
        ProtocolStateSpecification stateSpecification = SPECIFICATIONS.get(protocolState);
        if (stateSpecification == null) return null;
        return stateSpecification.specificationFor(packetClass);
    }

    /**
     * Represents a specification of a packet, which was registered in {@linkplain ServerPacketRegistry a server packet
     * registry}.
     *
     * @param packetIdentifier an identifier of the packet
     * @param packetClass a class of the packet
     * @param packetWriter a network writer, which writes the packet
     * @param <P> a type of the packet
     * @since 1.0
     * @see ServerPacketRegistry
     */
    public record RegistryPacketSpecification<P extends ServerPacket>(int packetIdentifier,
                                                                      @NonNull Class<P> packetClass,
                                                                      @NonNull NetworkWriter<P> packetWriter) {
        /**
         * Constructs the {@linkplain RegistryPacketSpecification registry packet specification}.
         *
         * @param packetIdentifier an identifier of the packet
         * @param packetClass a class of the packet
         * @param packetWriter a network writer, which writes the packet
         * @since 1.0
         */
        public RegistryPacketSpecification {
            NullabilityUtil.requireNonNull(packetClass, "packet class");
            NullabilityUtil.requireNonNull(packetWriter, "packet writer");
        }
    }

    /**
     * Represents a specification of {@linkplain ProtocolState a protocol state}, which holds all
     * {@linkplain NetworkWriter network writers}, which write packets during that protocol state.
     *
     * @since 1.0
     * @see ProtocolState
     * @see NetworkWriter
     */
    private static final class ProtocolStateSpecification {

        private final Map<Class<? extends ServerPacket>, RegistryPacketSpecification<?>> classToSpecificationMap;

        /**
         * Constructs the {@linkplain ProtocolStateSpecification protocol state specification}.
         *
         * @param entries a collection of entries that should be registered in the specification
         * @param specificationResourceFileName a name of a resource file containing all identifiers of the packets
         * @since 1.0
         */
        private ProtocolStateSpecification(@NonNull Set<Entry<?>> entries,
                                           @NonNull String specificationResourceFileName) {
            NullabilityUtil.requireNonNull(entries, "entries");
            NullabilityUtil.requireNonNull(specificationResourceFileName, "specification resource file name");

            List<DataRegistryEntry<?>> registryEntries = JetMinecraftRegistry.entries(
                    JetDataJson.createPacketGson(),
                    specificationResourceFileName
            );

            Map<Key, Integer> packetKeyToIdentifierMap = new HashMap<>();
            for (DataRegistryEntry<?> registryEntry : registryEntries) {
                // TODO: Replace with primitive type when it finally gets implemented in java
                if (!(registryEntry.value() instanceof Integer identifier))
                    throw new IllegalArgumentException("The value is not an integer");
                packetKeyToIdentifierMap.put(registryEntry.key(), identifier);
            }

            Map<Class<? extends ServerPacket>, RegistryPacketSpecification<?>> specifications = new HashMap<>();
            for (Entry<?> entry : entries) {
                Key packetKey = entry.packetKey();
                Integer packetIdentifier = packetKeyToIdentifierMap.get(packetKey);

                if (packetIdentifier == null) {
                    throw new IllegalArgumentException(String.format(
                            "Could not find a packet identifier for a key of %s", packetKey
                    ));
                }

                specifications.put(entry.packetClass(), entry.toSpecification(packetIdentifier));
            }

            this.classToSpecificationMap = Map.copyOf(specifications);
        }

        /**
         * Gets {@linkplain RegistryPacketSpecification a registry packet specification} for a packet with
         * a class specified.
         *
         * @param packetClass a class of the packet
         * @return the registry packet specification, {@code null} if not present
         * @since 1.0
         */
        private @Nullable RegistryPacketSpecification<?> specificationFor(
                @NonNull Class<? extends ServerPacket> packetClass
        ) {
            return this.classToSpecificationMap.get(NullabilityUtil.requireNonNull(packetClass, "packet class"));
        }

        /**
         * Represents a builder of {@linkplain ProtocolStateSpecification a protocol state specification}.
         *
         * @since 1.0
         * @see ProtocolStateSpecification
         */
        private static final class Builder {

            private final Set<Entry<?>> entries = new HashSet<>();
            private final String specificationResourceFileName;

            /**
             * Constructs the {@linkplain Builder builder}.
             *
             * @param specificationResourceFileName a name of a resource file containing all identifiers of the packets
             * @since 1.0
             */
            private Builder(@NonNull String specificationResourceFileName) {
                this.specificationResourceFileName = NullabilityUtil.requireNonNull(specificationResourceFileName,
                        "specification resource file name");
            }

            /**
             * Creates and adds {@linkplain Entry an entry} of the {@linkplain ProtocolStateSpecification protocol
             * state specification} to the builder.
             *
             * @param packetKey a key of the packet
             * @param packetClass a class of the packet
             * @param packetWriter a network writer of the packet
             * @return this builder
             * @param <P> a type of the packet
             * @since 1.0
             */
            private <P extends ServerPacket> @NonNull Builder add(@NonNull Key packetKey,
                                                                  @NonNull Class<P> packetClass,
                                                                  @NonNull NetworkWriter<P> packetWriter) {
                NullabilityUtil.requireNonNull(packetKey, "packet key");
                NullabilityUtil.requireNonNull(packetClass, "packet class");
                NullabilityUtil.requireNonNull(packetWriter, "packet writer");
                this.entries.add(new Entry<>(packetKey, packetClass, packetWriter));
                return this;
            }

            /**
             * Builds {@linkplain ProtocolStateSpecification a protocol state specification} using all data
             * specified in this builder.
             *
             * @return the packet
             * @since 1.0
             */
            private @NonNull ProtocolStateSpecification build() {
                return new ProtocolStateSpecification(Set.copyOf(this.entries), this.specificationResourceFileName);
            }
        }

        /**
         * Represents an entry of the {@linkplain ProtocolStateSpecification protocol state specification}.
         *
         * @param packetKey a key of the packet
         * @param packetClass a class of the packet
         * @param packetWriter a network writer, which writes the packet
         * @param <P> a type of the packet
         * @since 1.0
         */
        private record Entry<P extends ServerPacket>(@NonNull Key packetKey, @NonNull Class<P> packetClass,
                                                     @NonNull NetworkWriter<P> packetWriter) {
            /**
             * Constructs the {@linkplain Entry entry}.
             *
             * @param packetKey a key of the packet
             * @param packetClass a class of the packet
             * @param packetWriter a network writer, which writes the packet
             * @since 1.0
             */
            private Entry {
                NullabilityUtil.requireNonNull(packetKey, "packet key");
                NullabilityUtil.requireNonNull(packetClass, "packet class");
                NullabilityUtil.requireNonNull(packetWriter, "packet writer");
            }

            /**
             * Converts this entry to {@linkplain RegistryPacketSpecification a registry packet specification}.
             *
             * @param packetIdentifier an identifier of the packet
             * @return the packet specification
             * @since 1.0
             */
            private @NonNull RegistryPacketSpecification<P> toSpecification(int packetIdentifier) {
                return new RegistryPacketSpecification<>(packetIdentifier, this.packetClass, this.packetWriter);
            }
        }
    }
}