package net.hypejet.jet.server.network.packet.packets.client;

import io.netty.util.collection.IntObjectHashMap;
import io.netty.util.collection.IntObjectMap;
import net.hypejet.jet.data.autogenerated.server.ClientConfigurationPackets;
import net.hypejet.jet.data.autogenerated.server.ClientHandshakePackets;
import net.hypejet.jet.data.autogenerated.server.ClientLoginPackets;
import net.hypejet.jet.data.autogenerated.server.ClientPlayPackets;
import net.hypejet.jet.data.autogenerated.server.ClientStatusPackets;
import net.hypejet.jet.data.autogenerated.server.ResourceFileNames;
import net.hypejet.jet.data.codecs.JetDataJson;
import net.hypejet.jet.data.model.api.utils.NullabilityUtil;
import net.hypejet.jet.data.model.server.registry.registries.registry.DataRegistryEntry;
import net.hypejet.jet.server.network.ProtocolState;
import net.hypejet.jet.server.network.codec.NetworkReader;
import net.hypejet.jet.server.network.packet.handler.ClientPacketHandler;
import net.hypejet.jet.server.network.packet.handler.common.ClientCookieResponsePacketHandler;
import net.hypejet.jet.server.network.packet.handler.common.ClientInformationPacketHandler;
import net.hypejet.jet.server.network.packet.handler.common.ClientKeepAlivePacketHandler;
import net.hypejet.jet.server.network.packet.handler.common.ClientPluginMessagePacketHandler;
import net.hypejet.jet.server.network.packet.handler.common.ClientPongPacketHandler;
import net.hypejet.jet.server.network.packet.handler.common.ClientResourcePackStatePacketHandler;
import net.hypejet.jet.server.network.packet.handler.configuration.ClientAcknowledgeFinishConfigurationPacketHandler;
import net.hypejet.jet.server.network.packet.handler.configuration.ClientKnownPacksConfigurationPacketHandler;
import net.hypejet.jet.server.network.packet.handler.handshake.HandshakePacketHandler;
import net.hypejet.jet.server.network.packet.handler.login.ClientEncryptionResponseLoginPacketHandler;
import net.hypejet.jet.server.network.packet.handler.login.ClientLoginAcknowledgeLoginPacketHandler;
import net.hypejet.jet.server.network.packet.handler.login.ClientLoginRequestLoginPacketHandler;
import net.hypejet.jet.server.network.packet.handler.login.ClientPluginMessageResponseLoginPacketHandler;
import net.hypejet.jet.server.network.packet.handler.play.ClientChatCommandPlayPacketHandler;
import net.hypejet.jet.server.network.packet.handler.play.ClientCommandSuggestionsRequestPlayPacketHandler;
import net.hypejet.jet.server.network.packet.handler.status.ClientPingRequestStatusPacketHandler;
import net.hypejet.jet.server.network.packet.handler.status.ClientServerListRequestStatusPacketHandler;
import net.hypejet.jet.server.network.codec.packet.client.common.ClientCookieResponsePacketReader;
import net.hypejet.jet.server.network.codec.packet.client.common.ClientInformationPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.common.ClientKeepAlivePacketReader;
import net.hypejet.jet.server.network.codec.packet.client.common.ClientPluginMessagePacketReader;
import net.hypejet.jet.server.network.codec.packet.client.common.ClientPongPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.common.ClientResourcePackStatePacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientAcknowledgeMessagePlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientActionPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientChangeDifficultyPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientChatCommandPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientChatSessionUpdatePlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientCommandSuggestionsRequestPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientConfirmTeleportationPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientEndTickPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientPositionFlagsPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientPositionPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientQueryBlockEntityTagPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientRequestActionPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientRotationAndPositionPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientRotationPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientSignedChatCommandPlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.play.ClientSignedChatMessagePlayPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.configuration.ClientAcknowledgeFinishConfigurationPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.configuration.ClientKnownPacksConfigurationPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.handshake.HandshakePacketReader;
import net.hypejet.jet.server.network.codec.packet.client.login.ClientEncryptionResponseLoginPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.login.ClientLoginAcknowledgeLoginPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.login.ClientLoginRequestLoginPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.login.ClientPluginMessageResponseLoginPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.common.ClientPingRequestPacketReader;
import net.hypejet.jet.server.network.codec.packet.client.status.ClientServerListRequestStatusPacketReader;
import net.hypejet.jet.server.registry.JetMinecraftRegistry;
import net.kyori.adventure.key.Key;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

import java.util.EnumMap;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Represents a registry of {@linkplain NetworkReader network readers}, which
 * read {@linkplain ClientPacket client packets} and {@linkplain ClientPacketHandler client packet handlers}.
 *
 * @since 1.0
 * @author Codestech
 * @see ClientPacket
 * @see NetworkReader
 */
public final class ClientPacketRegistry {

    private static final Map<ProtocolState, ProtocolStateSpecification> SPECIFICATIONS;
    private static final Map<Class<? extends ClientPacket>, ClientPacketHandler<?>> HANDLERS = new HandlersBuilder()
            // Handshake packets
            .add(new HandshakePacketHandler())
            // Login packets
            .add(new ClientEncryptionResponseLoginPacketHandler())
            .add(new ClientLoginAcknowledgeLoginPacketHandler())
            .add(new ClientLoginRequestLoginPacketHandler())
            .add(new ClientPluginMessageResponseLoginPacketHandler())
            // Status packets
            .add(new ClientPingRequestStatusPacketHandler())
            .add(new ClientServerListRequestStatusPacketHandler())
            // Configuration packets
            .add(new ClientAcknowledgeFinishConfigurationPacketHandler())
            .add(new ClientKnownPacksConfigurationPacketHandler())
            // Play packets
            .add(new ClientChatCommandPlayPacketHandler())
            .add(new ClientCommandSuggestionsRequestPlayPacketHandler())
            // Common packets
            .add(new ClientCookieResponsePacketHandler())
            .add(new ClientInformationPacketHandler())
            .add(new ClientKeepAlivePacketHandler())
            .add(new ClientPluginMessagePacketHandler())
            .add(new ClientPongPacketHandler())
            .add(new ClientResourcePackStatePacketHandler())
            .build();

    static {
        Map<ProtocolState, ProtocolStateSpecification> specifications = new EnumMap<>(ProtocolState.class);

        ClientCookieResponsePacketReader cookieResponseReader = new ClientCookieResponsePacketReader();
        ClientPongPacketReader pongReader = new ClientPongPacketReader();
        ClientKeepAlivePacketReader keepAliveReader = new ClientKeepAlivePacketReader();
        ClientPluginMessagePacketReader pluginMessageReader = new ClientPluginMessagePacketReader();
        ClientInformationPacketReader clientInformationReader = new ClientInformationPacketReader();
        ClientResourcePackStatePacketReader resourcePackStateReader = new ClientResourcePackStatePacketReader();
        ClientPingRequestPacketReader pingRequestReader = new ClientPingRequestPacketReader();

        specifications.put(
                ProtocolState.HANDSHAKE,
                new ProtocolStateSpecification.Builder(ResourceFileNames.CLIENT_HANDSHAKE_PACKET_GENERATOR)
                        .add(ClientHandshakePackets.INTENTION, new HandshakePacketReader())
                        .build()
        );

        specifications.put(
                ProtocolState.STATUS,
                new ProtocolStateSpecification.Builder(ResourceFileNames.CLIENT_STATUS_PACKET_GENERATOR)
                        .add(ClientStatusPackets.STATUS_REQUEST, new ClientServerListRequestStatusPacketReader())
                        .add(ClientStatusPackets.PING_REQUEST, pingRequestReader)
                        .build()
        );

        specifications.put(
                ProtocolState.LOGIN,
                new ProtocolStateSpecification.Builder(ResourceFileNames.CLIENT_LOGIN_PACKET_GENERATOR)
                        .add(ClientLoginPackets.COOKIE_RESPONSE, cookieResponseReader)
                        .add(ClientLoginPackets.HELLO, new ClientLoginRequestLoginPacketReader())
                        .add(ClientLoginPackets.KEY, new ClientEncryptionResponseLoginPacketReader())
                        .add(ClientLoginPackets.LOGIN_ACKNOWLEDGED, new ClientLoginAcknowledgeLoginPacketReader())
                        .add(ClientLoginPackets.CUSTOM_QUERY_ANSWER,
                                new ClientPluginMessageResponseLoginPacketReader())
                        .build()
        );

        specifications.put(
                ProtocolState.CONFIGURATION,
                new ProtocolStateSpecification.Builder(ResourceFileNames.CLIENT_CONFIGURATION_PACKET_GENERATOR)
                        .add(ClientConfigurationPackets.PONG, pongReader)
                        .add(ClientConfigurationPackets.KEEP_ALIVE, keepAliveReader)
                        .add(ClientConfigurationPackets.CUSTOM_PAYLOAD, pluginMessageReader)
                        .add(ClientConfigurationPackets.CLIENT_INFORMATION, clientInformationReader)
                        .add(ClientConfigurationPackets.COOKIE_RESPONSE, cookieResponseReader)
                        .add(ClientConfigurationPackets.RESOURCE_PACK, resourcePackStateReader)
                        .add(ClientConfigurationPackets.FINISH_CONFIGURATION,
                                new ClientAcknowledgeFinishConfigurationPacketReader())
                        .add(ClientConfigurationPackets.SELECT_KNOWN_PACKS,
                                new ClientKnownPacksConfigurationPacketReader())
                        .build()
        );

        specifications.put(
                ProtocolState.PLAY,
                new ProtocolStateSpecification.Builder(ResourceFileNames.CLIENT_PLAY_PACKET_GENERATOR)
                        .add(ClientPlayPackets.KEEP_ALIVE, keepAliveReader)
                        .add(ClientPlayPackets.CUSTOM_PAYLOAD, pluginMessageReader)
                        .add(ClientPlayPackets.CLIENT_INFORMATION, clientInformationReader)
                        .add(ClientPlayPackets.PONG, pongReader)
                        .add(ClientPlayPackets.COOKIE_RESPONSE, cookieResponseReader)
                        .add(ClientPlayPackets.RESOURCE_PACK, resourcePackStateReader)
                        .add(ClientPlayPackets.PING_REQUEST, pingRequestReader)
                        .add(ClientPlayPackets.MOVE_PLAYER_POS_ROT, new ClientRotationAndPositionPlayPacketReader())
                        .add(ClientPlayPackets.MOVE_PLAYER_ROT, new ClientRotationPlayPacketReader())
                        .add(ClientPlayPackets.MOVE_PLAYER_POS, new ClientPositionPlayPacketReader())
                        .add(ClientPlayPackets.MOVE_PLAYER_STATUS_ONLY, new ClientPositionFlagsPlayPacketReader())
                        .add(ClientPlayPackets.PLAYER_COMMAND, new ClientActionPlayPacketReader())
                        .add(ClientPlayPackets.ACCEPT_TELEPORTATION, new ClientConfirmTeleportationPlayPacketReader())
                        .add(ClientPlayPackets.BLOCK_ENTITY_TAG_QUERY, new ClientQueryBlockEntityTagPacketReader())
                        .add(ClientPlayPackets.CHANGE_DIFFICULTY, new ClientChangeDifficultyPlayPacketReader())
                        .add(ClientPlayPackets.CHAT_ACK, new ClientAcknowledgeMessagePlayPacketReader())
                        .add(ClientPlayPackets.CHAT_COMMAND, new ClientChatCommandPlayPacketReader())
                        .add(ClientPlayPackets.CHAT_COMMAND_SIGNED, new ClientSignedChatCommandPlayPacketReader())
                        .add(ClientPlayPackets.CHAT, new ClientSignedChatMessagePlayPacketReader())
                        .add(ClientPlayPackets.CHAT_SESSION_UPDATE, new ClientChatSessionUpdatePlayPacketReader())
                        .add(ClientPlayPackets.CLIENT_COMMAND, new ClientRequestActionPlayPacketReader())
                        .add(ClientPlayPackets.CLIENT_TICK_END, new ClientEndTickPlayPacketReader())
                        .add(ClientPlayPackets.COMMAND_SUGGESTION,
                                new ClientCommandSuggestionsRequestPlayPacketReader())
                        .build()
        );

        SPECIFICATIONS = specifications;
    }

    private ClientPacketRegistry() {}

    /**
     * Gets {@linkplain NetworkReader a client packet network reader} for a packet specified, which was registered in
     * this registry.
     *
     * @param packetId an identifier of the packet
     * @param protocolState a protocol state, during which the packet is handled
     * @return the client packet network reader, {@code null} if not present
     * @since 1.0
     */
    public static @Nullable NetworkReader<? extends ClientPacket> readerFor(int packetId,
                                                                            @NonNull ProtocolState protocolState) {
        NullabilityUtil.requireNonNull(protocolState, "protocol state");
        ProtocolStateSpecification specification = SPECIFICATIONS.get(protocolState);
        if (specification == null) return null;
        return specification.readerFor(packetId);
    }

    /**
     * Gets {@linkplain ClientPacketHandler a client packet handler} for a client packet with class specified.
     *
     * @param packetClass the class
     * @return the client packet handler
     * @since 1.0
     */
    public static @Nullable ClientPacketHandler<?> handlerFor(@NonNull Class<? extends ClientPacket> packetClass) {
        return HANDLERS.get(packetClass);
    }

    /**
     * Represents a specification of {@linkplain ProtocolState a protocol state}, which holds all
     * {@linkplain NetworkReader client packet network readers}, which handle packets during that protocol state.
     *
     * @since 1.0
     * @see ProtocolState
     * @see NetworkReader
     */
    private static final class ProtocolStateSpecification {

        private final IntObjectMap<NetworkReader<? extends ClientPacket>> identifierToReaderMap;

        /**
         * Constructs the {@linkplain ProtocolStateSpecification protocol state specification}.
         *
         * @param entries a collection of entries that should be registered in the specification
         * @param specificationResourceFileName a name of a resource file containing all identifiers of the packets
         * @since 1.0
         */
        private ProtocolStateSpecification(@NonNull Set<Entry<?>> entries,
                                           @NonNull String specificationResourceFileName) {
            NullabilityUtil.requireNonNull(entries, "entries");
            NullabilityUtil.requireNonNull(specificationResourceFileName, "specification resource file name");

            List<DataRegistryEntry<?>> registryEntries = JetMinecraftRegistry.entries(
                    JetDataJson.createPacketGson(),
                    specificationResourceFileName
            );

            Map<Key, Integer> packetKeyToIdentifierMap = new HashMap<>();
            for (DataRegistryEntry<?> registryEntry : registryEntries) {
                // TODO: Replace with primitive type when it finally gets implemented in java
                if (!(registryEntry.value() instanceof Integer identifier))
                    throw new IllegalArgumentException("The value is not an integer");
                packetKeyToIdentifierMap.put(registryEntry.key(), identifier);
            }

            IntObjectMap<NetworkReader<? extends ClientPacket>> identifierToReaderMap = new IntObjectHashMap<>();
            for (Entry<?> entry : entries) {
                Key packetKey = entry.packetKey();
                Integer packetIdentifier = packetKeyToIdentifierMap.get(packetKey);

                if (packetIdentifier == null) {
                    throw new IllegalArgumentException(String.format(
                            "Could not find a packet identifier for a key of %s", packetKey
                    ));
                }

                identifierToReaderMap.put(packetIdentifier, entry.reader());
            }

            this.identifierToReaderMap = identifierToReaderMap;
        }

        /**
         * Gets {@linkplain NetworkReader a client packet network reader} for a packet with an identifier specified.
         *
         * @param packetIdentifier the packet identifier
         * @return the client packet network reader
         * @since 1.0
         */
        private @Nullable NetworkReader<? extends ClientPacket> readerFor(int packetIdentifier) {
            return this.identifierToReaderMap.get(packetIdentifier);
        }

        /**
         * Represents a builder of {@linkplain ProtocolStateSpecification a protocol state specification}.
         *
         * @since 1.0
         * @see ProtocolStateSpecification
         */
        private static final class Builder {

            private final String specificationResourceFileName;
            private final Set<Entry<?>> entries = new HashSet<>();

            /**
             * Constructs the {@linkplain Builder builder}.
             *
             * @param specificationResourceFileName a name of a resource file containing all identifiers of the packets
             * @since 1.0
             */
            private Builder(@NonNull String specificationResourceFileName) {
                this.specificationResourceFileName = NullabilityUtil.requireNonNull(specificationResourceFileName,
                        "specification resource file name");
            }

            /**
             * Creates and adds {@linkplain Entry an entry} of the {@linkplain ProtocolStateSpecification protocol
             * state specification} to the builder.
             *
             * @param packetKey a key of the packet
             * @param reader a network reader of the packet
             * @return this builder
             * @param <P> a type of the packet
             * @since 1.0
             */
            private <P extends ClientPacket> @NonNull Builder add(@NonNull Key packetKey,
                                                                  @NonNull NetworkReader<P> reader) {
                NullabilityUtil.requireNonNull(packetKey, "packet key");
                NullabilityUtil.requireNonNull(reader, "reader");
                this.entries.add(new Entry<>(packetKey, reader));
                return this;
            }

            /**
             * Builds {@linkplain ProtocolStateSpecification a protocol state specification} using all data
             * specified in this builder.
             *
             * @return the packet
             * @since 1.0
             */
            private @NonNull ProtocolStateSpecification build() {
                return new ProtocolStateSpecification(Set.copyOf(this.entries), this.specificationResourceFileName);
            }
        }

        /**
         * Represents an entry of the {@linkplain ProtocolStateSpecification protocol state specification}.
         *
         * @param packetKey a key of the packet
         * @param reader a network reader of the packet
         * @param <P> a type of the packet
         * @since 1.0
         */
        private record Entry<P extends ClientPacket>(@NonNull Key packetKey, @NonNull NetworkReader<P> reader) {
            /**
             * Constructs the {@linkplain Entry entry}.
             *
             * @param packetKey a key of the packet
             * @param reader a network reader of the packet
             * @since 1.0
             */
            private Entry {
                NullabilityUtil.requireNonNull(packetKey, "packet key");
                NullabilityUtil.requireNonNull(reader, "reader");
            }
        }
    }


    /**
     * Represents a builder of {@linkplain Map a map} mapping classes of {@linkplain ClientPacket client packets}
     * to their {@linkplain ClientPacketHandler client packet handlers}.
     *
     * @since 1.0
     * @see ClientPacket
     * @see ClientPacketHandler
     * @see Map
     */
    private static final class HandlersBuilder {

        private final Map<Class<? extends ClientPacket>, ClientPacketHandler<?>> handlers = new HashMap<>();

        /**
         * Adds a mapping for a client packet.
         *
         * @param handler a handler of the client packet
         * @return this builder
         * @param <P> a type of the client packet
         * @since 1.0
         */
        private <P extends ClientPacket> @NonNull HandlersBuilder add(@NonNull ClientPacketHandler<P> handler) {
            this.handlers.put(handler.packetClass(), handler);
            return this;
        }

        /**
         * Creates the map using mapping registered in this builder.
         *
         * @return the map
         * @since 1.0
         */
        private @NonNull Map<Class<? extends ClientPacket>, ClientPacketHandler<?>> build() {
            return Map.copyOf(this.handlers);
        }
    }
}