package net.hypejet.jet.data.generator.generator;

import org.jetbrains.annotations.NotNull;

import java.nio.file.Path;

/**
 * Represents a {@linkplain Generator generator} generating contents a resource file.
 *
 * @since 1.0
 * @see Generator
 */
public non-sealed interface ResourceGenerator extends Generator {
    /**
     * Generates the resource file contents.
     *
     * @return the contents as string
     * @since 1.0
     */
    @NotNull String generate();

    /**
     * Gets a relative {@linkplain Path path} of a file that should have the output generated by this
     * {@linkplain ResourceGenerator resource generator}.
     *
     * @return the path
     * @since 1.0
     */
    @NotNull Path path();
}