package net.hypejet.jet.protocol.packet.server.login;

import net.hypejet.jet.protocol.packet.server.ServerLoginPacket;
import org.checkerframework.checker.nullness.qual.NonNull;

/**
 * Represents a {@linkplain ServerLoginPacket server login packet}, which requests an encryption from a Minecraft
 * client.
 *
 * @param serverId an identifier of a server requesting the encryption
 * @param publicKey a public key of a server requesting the encryption
 * @param verifyToken a verify token, which is a random sequence of bytes generated by a server requesting the
 *                    encryption
 * @param shouldAuthenticate whether the client should authenticate with Mojang
 * @since 1.0
 * @author Codestech
 * @see ServerLoginPacket
 */
public record ServerEncryptionRequestLoginPacket(@NonNull String serverId, byte @NonNull [] publicKey,
                                                 byte @NonNull [] verifyToken, boolean shouldAuthenticate)
        implements ServerLoginPacket {}