package net.hypejet.jet.server.world.chunk;

import net.hypejet.jet.data.autogenerated.api.Blocks;
import net.hypejet.jet.data.model.api.registries.biome.Biome;
import net.hypejet.jet.data.model.api.registries.dimension.DimensionType;
import net.hypejet.jet.data.model.api.utils.NullabilityUtil;
import net.hypejet.jet.data.model.server.registry.registries.block.state.BlockState;
import net.hypejet.jet.registry.RegistryEntry;
import net.hypejet.jet.server.registry.JetMinecraftRegistry;
import net.hypejet.jet.server.registry.JetRegistryEntry;
import net.hypejet.jet.server.registry.JetRegistryManager;
import net.hypejet.jet.server.world.JetWorld;
import net.hypejet.jet.server.world.block.BlockType;
import net.hypejet.jet.server.world.chunk.heightmap.HeightMap;
import net.hypejet.jet.server.world.chunk.heightmap.HeightMapType;
import net.hypejet.jet.server.world.chunk.light.LightSection;
import net.hypejet.jet.server.world.chunk.light.LightSectionList;
import net.hypejet.jet.server.world.chunk.palette.type.ChunkPaletteType;
import net.hypejet.jet.server.world.chunk.section.ChunkSection;
import net.hypejet.jet.server.world.chunk.section.ChunkSectionList;
import net.hypejet.jet.server.world.chunk.update.BiomeUpdate;
import net.hypejet.jet.server.world.chunk.update.BlockStateUpdate;
import net.hypejet.jet.server.world.chunk.update.LightUpdate;
import net.hypejet.jet.server.world.coordinate.relative.ChunkRelativePosition;
import net.hypejet.jet.world.block.entity.BlockEntity;
import net.hypejet.jet.world.chunk.ChunkBuilder;
import net.kyori.adventure.key.Key;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * Represents part of {@linkplain JetWorld a world}.
 *
 * @since 1.0
 * @see JetWorld
 */
public final class Chunk {

    private final JetWorld world;

    private final ChunkSectionList chunkSectionList;
    private final LightSectionList lightSectionList;

    private final Set<HeightMap> heightMaps;
    private final Map<ChunkRelativePosition, BlockEntity> blockEntities;

    /**
     * Constructs the {@linkplain Chunk chunk}.
     *
     * @param world a world that should own the chunk
     * @param chunkSectionList a chunk section list, which contains all chunk sections that the chunk should have
     * @param lightSectionList a light section list, which contains all light sections that the chunk should have
     * @param heightMaps a set of height maps that the chunk should have
     * @param blockEntities a map, which maps chunk relative positions of blocks that the chunk should have
     *                      to block entities associated with them
     * @since 1.0
     */
    private Chunk(@NonNull JetWorld world, @NonNull ChunkSectionList chunkSectionList,
                  @NonNull LightSectionList lightSectionList, @NonNull Set<HeightMap> heightMaps,
                  @NonNull Map<ChunkRelativePosition, BlockEntity> blockEntities) {
        this.world = NullabilityUtil.requireNonNull(world, "world");

        this.chunkSectionList = NullabilityUtil.requireNonNull(chunkSectionList, "chunk section list");
        this.lightSectionList = NullabilityUtil.requireNonNull(lightSectionList, "light section list");

        this.heightMaps = Set.copyOf(NullabilityUtil.requireNonNull(heightMaps, "height maps"));
        this.blockEntities = Map.copyOf(NullabilityUtil.requireNonNull(blockEntities, "block entities"));
    }

    /**
     * Gets {@linkplain JetWorld a world} that owns this chunk.
     *
     * @return the world
     * @since 1.0
     */
    public @NonNull JetWorld world() {
        return this.world;
    }

    /**
     * Gets {@linkplain ChunkSectionList a chunk section list}, which stores
     * all {@linkplain ChunkSection chunk sections} of this chunk.
     *
     * @return the chunk section list
     * @since 1.0
     */
    public @NonNull ChunkSectionList chunkSectionList() {
        return this.chunkSectionList;
    }

    /**
     * Gets {@linkplain LightSectionList a light section list}, which stores
     * all {@linkplain LightSection light sections} of this chunk.
     *
     * @return the light section list
     * @since 1.0
     */
    public @NonNull LightSectionList lightSectionList() {
        return this.lightSectionList;
    }

    /**
     * Gets {@linkplain Set a set} of {@linkplain HeightMap height maps} of the chunk.
     *
     * @return the set
     * @since 1.0
     */
    public @NonNull Set<HeightMap> heightMaps() {
        return this.heightMaps;
    }

    /**
     * Gets {@linkplain Map a map}, which maps {@linkplain ChunkRelativePosition chunk relative positions} of blocks
     * of this chunk to {@linkplain BlockEntity block entities} of them.
     *
     * @return the set
     * @since 1.0
     */
    public @NonNull Map<ChunkRelativePosition, BlockEntity> blockEntities() {
        return this.blockEntities;
    }

    /**
     * Creates {@linkplain Chunk a chunk}, which is a copy of this chunk with updates specified applied.
     *
     * @param blockStateUpdates updates that should be applied to block states
     * @param biomeUpdates updates that should be applied to biomes
     * @param lightUpdates updates that should be applied to light
     * @return the chunk created
     * @since 1.0
     */
    public @NonNull Chunk withUpdates(@NonNull Collection<BlockStateUpdate> blockStateUpdates,
                                      @NonNull Collection<BiomeUpdate> biomeUpdates,
                                      @NonNull Collection<LightUpdate> lightUpdates) {
        ChunkSectionList chunkSectionList = this.chunkSectionList.withUpdates(blockStateUpdates, biomeUpdates);
        LightSectionList lightSectionList = this.lightSectionList.withUpdates(lightUpdates);

        Set<HeightMap> heightMaps = new HashSet<>();
        for (HeightMap heightMap : this.heightMaps)
            heightMaps.add(heightMap.withUpdates(chunkSectionList, blockStateUpdates));

        // TODO: Handle block entity updates
        return new Chunk(this.world, chunkSectionList, lightSectionList, heightMaps, this.blockEntities);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Chunk otherChunk)) return false;
        return Objects.equals(this.world, otherChunk.world)
                && Objects.equals(this.chunkSectionList, otherChunk.chunkSectionList)
                && Objects.equals(this.lightSectionList, otherChunk.lightSectionList)
                && Objects.equals(this.heightMaps, otherChunk.heightMaps)
                && Objects.equals(this.blockEntities, otherChunk.blockEntities);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.world, this.chunkSectionList,
                this.lightSectionList, this.heightMaps, this.blockEntities);
    }

    @Override
    public String toString() {
        return "Chunk{" +
                "dimensionType=" + this.world +
                ", chunkSectionList=" + this.chunkSectionList +
                ", lightSectionList=" + this.lightSectionList +
                ", heightMaps=" + this.heightMaps +
                ", blockEntities=" + this.blockEntities +
                '}';
    }

    /**
     * Represents a builder of {@linkplain Chunk a chunk} and implementation
     * of {@linkplain ChunkBuilder a chunk builder}.
     *
     * @since 1.0
     * @see Chunk
     * @see ChunkBuilder
     */
    public static final class Builder implements ChunkBuilder {

        private final JetWorld world;

        private final ChunkSectionList.Builder chunkSectionListBuilder;
        private final LightSectionList.Builder lightSectionListBuilder;

        private final Map<ChunkRelativePosition, BlockEntity> blockEntities = new HashMap<>();

        /**
         * Constructs the {@linkplain Builder chunk builder}.
         *
         * @param world a world that the chunk is created for
         * @param defaultBiome a registry entry of a biome that should be used where a biome has not been set
         * @since 1.0
         */
        public Builder(@NonNull JetWorld world, @NonNull JetRegistryEntry<Biome> defaultBiome) {
            this.world = NullabilityUtil.requireNonNull(world, "world");
            NullabilityUtil.requireNonNull(defaultBiome, "default biome");

            DimensionType dimensionType = world.dimensionType().value();
            JetRegistryManager registryManager = world.worldManager().server().registryManager();

            JetRegistryEntry<BlockType> defaultBlockTypeEntry = registryManager.blockTypeRegistry().get(Blocks.AIR);
            if (defaultBlockTypeEntry == null)
                throw new IllegalStateException("Could not find an air block");

            this.chunkSectionListBuilder = new ChunkSectionList.Builder(
                    dimensionType, registryManager.blockStateOrder(),
                    registryManager.biomeRegistry().elementOrder(),
                    defaultBlockTypeEntry.value().defaultState(), defaultBiome
            );

            this.lightSectionListBuilder = new LightSectionList.Builder(dimensionType);
        }

        @Override
        public void setBlock(byte x, short y, byte z, @NonNull Key blockTypeKey) {
            this.setBlock(x, y, z, blockTypeKey, null, null);
        }

        @Override
        public void setBlock(byte x, short y, byte z, @NonNull Key blockTypeKey, @Nullable BlockEntity blockEntity) {
            this.setBlock(x, y, z, blockTypeKey, null, blockEntity);
        }

        @Override
        public void setBlock(byte x, short y, byte z, @NonNull Key blockTypeKey,
                             @Nullable Map<String, String> properties) {
            this.setBlock(x, y, z, blockTypeKey, properties, null);
        }

        @Override
        public void setBlock(byte x, short y, byte z, @NonNull Key blockTypeKey,
                             @Nullable Map<String, String> properties, @Nullable BlockEntity blockEntity) {
            NullabilityUtil.requireNonNull(blockTypeKey, "block type key");

            JetRegistryManager registryManager = this.world.worldManager().server().registryManager();
            JetMinecraftRegistry<BlockType> blockTypeRegistry = registryManager.blockTypeRegistry();

            RegistryEntry<BlockType> blockTypeEntry = blockTypeRegistry.get(blockTypeKey);
            if (blockTypeEntry == null) {
                throw new IllegalArgumentException(String.format(
                        "Could not find a block type with key of %s",
                        blockTypeKey
                ));
            }

            BlockType blockType = blockTypeEntry.value();
            BlockState blockState = properties == null ? blockType.defaultState() : blockType.state(properties);

            ChunkRelativePosition position = new ChunkRelativePosition(x, y, z, ChunkPaletteType.BLOCK_STATE);

            if (blockEntity != null)
                this.blockEntities.put(position, blockEntity);
            this.chunkSectionListBuilder.setBlockState(position, blockState);
        }

        @Override
        public void setBiome(byte x, short y, byte z, @NonNull RegistryEntry<Biome> biome) {
            NullabilityUtil.requireNonNull(biome, "biome");
            if (!(biome instanceof JetRegistryEntry<Biome> validatedBiome))
                throw new IllegalArgumentException("The biome registry entry specified is not a valid registry entry");
            this.setBiome(new ChunkRelativePosition(x, y, z, ChunkPaletteType.BIOME), validatedBiome);
        }

        @Override
        public void setSkyLight(byte x, short y, byte z, byte value) {
            this.setSkyLight(new ChunkRelativePosition(x, y, z, ChunkPaletteType.BLOCK_STATE), value);
        }

        @Override
        public void setBlockLight(byte x, short y, byte z, byte value) {
            this.setBlockLight(new ChunkRelativePosition(x, y, z, ChunkPaletteType.BLOCK_STATE), value);
        }

        /**
         * Sets {@linkplain Biome a biome} that should be present
         * at {@linkplain ChunkRelativePosition a chunk-relative position} specified.
         *
         * @param position the chunk-relative position
         * @param biome a registry entry of the biome
         * @since 1.0
         */
        public void setBiome(@NonNull ChunkRelativePosition position, @NonNull JetRegistryEntry<Biome> biome) {
            NullabilityUtil.requireNonNull(position, "position");
            NullabilityUtil.requireNonNull(biome, "biome");
            this.chunkSectionListBuilder.setBiome(position, biome);
        }

        /**
         * Sets a skylight value that should be set for a block
         * at {@linkplain ChunkRelativePosition a chunk-relative position} specified.
         *
         * @param position the chunk-relative position
         * @param value the skylight value
         * @since 1.0
         */
        public void setSkyLight(@NonNull ChunkRelativePosition position, byte value) {
            NullabilityUtil.requireNonNull(position, "position");
            this.lightSectionListBuilder.setSkyLight(position, value);
        }

        /**
         * Sets a block light value that should be set for a block
         * at {@linkplain ChunkRelativePosition a chunk-relative position} specified.
         *
         * @param position the chunk-relative position
         * @param value the block light value
         * @since 1.0
         */
        public void setBlockLight(@NonNull ChunkRelativePosition position, byte value) {
            NullabilityUtil.requireNonNull(position, "position");
            this.lightSectionListBuilder.setBlockLight(position, value);
        }

        /**
         * Builds {@linkplain Chunk a chunk} with data set in this builder.
         *
         * @return the chunk
         * @since 1.0
         */
        public @NonNull Chunk build() {
            ChunkSectionList chunkSectionList = this.chunkSectionListBuilder.build();
            LightSectionList lightSectionList = this.lightSectionListBuilder.build();

            Set<HeightMap> heightMaps = new HashSet<>();
            for (HeightMapType heightMapType : HeightMapType.values())
                heightMaps.add(HeightMap.create(heightMapType, chunkSectionList, this.world.dimensionType().value()));

            return new Chunk(
                    this.world, chunkSectionList,
                    lightSectionList, Set.copyOf(heightMaps),
                    this.blockEntities
            );
        }
    }
}