package net.hypejet.jet.server.world.chunk.factory;

import net.hypejet.jet.data.autogenerated.api.Biomes;
import net.hypejet.jet.data.autogenerated.api.Blocks;
import net.hypejet.jet.data.model.api.registries.biome.Biome;
import net.hypejet.jet.data.model.api.registries.dimension.DimensionType;
import net.hypejet.jet.data.model.api.utils.NullabilityUtil;
import net.hypejet.jet.data.model.server.registry.registries.block.state.BlockState;
import net.hypejet.jet.registry.RegistryEntry;
import net.hypejet.jet.server.JetMinecraftServer;
import net.hypejet.jet.server.registry.JetMinecraftRegistry;
import net.hypejet.jet.server.registry.JetRegistryEntry;
import net.hypejet.jet.server.world.block.BlockType;
import net.hypejet.jet.server.world.chunk.JetChunk;
import net.hypejet.jet.server.world.chunk.builder.JetChunkBuilder;
import net.hypejet.jet.server.world.chunk.light.JetLightSection;
import net.hypejet.jet.server.world.chunk.section.JetChunkSection;
import net.hypejet.jet.world.block.entity.BlockEntity;
import net.hypejet.jet.world.chunk.factory.ChunkFactory;
import net.hypejet.jet.world.coordinate.chunk.relative.ChunkRelativeBlockPosition;
import net.kyori.adventure.key.Key;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

import java.util.List;
import java.util.Map;

/**
 * Represents an implementation of {@linkplain ChunkFactory a chunk factory}.
 *
 * @implSpec 1.0
 * @see ChunkFactory
 */
public final class JetChunkFactory implements ChunkFactory<JetChunkSection, JetLightSection, BlockState> {

    private final JetMinecraftServer server;

    /**
     * Constructs the {@linkplain JetChunkFactory chunk factory implementation}.
     *
     * @param server a server that should own chunks created by the factory
     * @since 1.0
     */
    public JetChunkFactory(@NonNull JetMinecraftServer server) {
        this.server = NullabilityUtil.requireNonNull(server, "server");
    }

    @Override
    public @NonNull JetChunk createChunk(@NonNull DimensionType dimensionType,
                                         @NonNull List<JetChunkSection> chunkSections,
                                         @NonNull List<JetLightSection> lightSections,
                                         @NonNull Map<ChunkRelativeBlockPosition, BlockEntity> blockEntities) {
        return JetChunk.create(this.server, dimensionType, chunkSections, lightSections, blockEntities);
    }

    @Override
    public @NonNull JetChunkBuilder createChunkBuilder(@NonNull DimensionType dimensionType) {
        JetRegistryEntry<Biome> biome = this.server.registryManager().biomeRegistry().get(Biomes.PLAINS);
        if (biome == null)
            throw new IllegalStateException("Could not find a plains biome");
        return this.createChunkBuilder(dimensionType, Blocks.AIR, null, null, biome);
    }

    @Override
    public @NonNull JetChunkBuilder createChunkBuilder(
            @NonNull DimensionType dimensionType, @NonNull Key defaultBlockTypeKey,
            @Nullable Map<String, String> properties, @Nullable BlockEntity defaultBlockEntity,
            @NonNull RegistryEntry<Biome> defaultBiome
    ) {
        if (!(defaultBiome instanceof JetRegistryEntry<Biome> validatedBiome))
            throw new IllegalArgumentException("The biome registry entry specified is not a valid registry entry");

        JetMinecraftRegistry<BlockType> blockTypeRegistry = this.server.registryManager().blockTypeRegistry();
        JetRegistryEntry<BlockType> blockTypeEntry = blockTypeRegistry.get(defaultBlockTypeKey);

        if (blockTypeEntry == null) {
            throw new IllegalArgumentException(String.format(
                    "Could not find a block type with key of %s",
                    defaultBlockTypeKey
            ));
        }

        BlockType blockType = blockTypeEntry.value();
        BlockState blockState = properties == null ? blockType.defaultState() : blockType.state(properties);

        return new JetChunkBuilder(dimensionType, this.server, blockState, validatedBiome, defaultBlockEntity);
    }
}