package net.hypejet.jet.server.configuration.unparsed;

import eu.okaeri.configs.OkaeriConfig;
import eu.okaeri.configs.annotation.Comment;
import eu.okaeri.configs.annotation.Comments;
import eu.okaeri.configs.annotation.CustomKey;
import eu.okaeri.configs.annotation.Header;
import eu.okaeri.configs.annotation.Headers;
import eu.okaeri.configs.yaml.snakeyaml.YamlSnakeYamlConfigurer;
import net.hypejet.jet.data.autogenerated.server.FeaturePacks;
import net.hypejet.jet.data.model.server.registry.registries.pack.FeaturePack;
import net.hypejet.jet.server.configuration.ConfigurationPlaceholder;
import net.hypejet.jet.server.network.netty.transport.NettyTransportSelector;
import net.hypejet.jet.util.game.ping.ServerListPing;
import net.kyori.adventure.key.Key;
import org.checkerframework.checker.nullness.qual.MonotonicNonNull;
import org.checkerframework.checker.nullness.qual.NonNull;

import java.nio.file.Path;
import java.util.HashSet;
import java.util.Set;

/**
 * Represents an unparsed configuration of {@linkplain net.hypejet.jet.server.JetMinecraftServer a Minecraft server}.
 *
 * <p>This was split up from {@linkplain net.hypejet.jet.server.configuration.JetServerConfiguration a server
 * configuration} to avoid placeholder and gradient issues with MiniMessage components.</p>
 *
 * @since 1.0
 * @see net.hypejet.jet.server.JetMinecraftServer
 */
@Headers({@Header("A main configuration file for the Jet sever software."), @Header("")})
public final class UnparsedServerConfiguration extends OkaeriConfig {
    @Comment("An address that the server should bind to.")
    private @MonotonicNonNull String address = defaultAddress();

    @Comment("A port that the server should bind to.")
    private int port = 25565;

    @Comment("A packet length, since which packets are compressed.")
    @CustomKey("compression-threshold")
    private int compressionThreshold = 256;

    @Comments({
            @Comment("A transport, which should be used by netty."),
            @Comment("Available options are NIO, EPOLL, KQUEUE and AUTO."),
            @Comment("AUTO will automatically select the most sufficient transport available.")
    })
    private @MonotonicNonNull NettyTransportSelector transport = NettyTransportSelector.AUTO;

    @Comment("A message used during disconnection when a player is trying to join with an unsupported version.")
    @CustomKey("unsupported-version-message")
    private @MonotonicNonNull String unsupportedVersionMessage = createDefaultUnsupportedVersionMessage();

    @Comment("A message used as a description of server list ping.")
    @CustomKey("server-list-description")
    private @MonotonicNonNull String serverListDescription = createDefaultServerListDescription();

    @Comments({
            @Comment("A max amount of the players, which can be on the server at once."),
            @Comment("Note that this value by default is used only by for server list pinging,"),
            @Comment("however, it might be used by other plugins for actually limiting the player count.")
    })
    @CustomKey("max-players")
    private int maxPlayers = 100;

    @Comments({
            @Comment("Feature packs that should be enabled on the server."),
            @Comment,
            @Comment("The feature packs add additional functionality on the server and client."),
            @Comment("Make sure that you put actual Minecraft feature pack keys here.")
    })
    @CustomKey("enabled-packs")
    private @MonotonicNonNull Set<Key> enabledFeaturePacks = createDefaultEnabledFeaturePacks();

    @Comment("Defines whether clients joining due a server transfer should be allowed.")
    @CustomKey("transfers-allowed")
    private boolean transfersAllowed = false;

    @Comment("A message used during disconnection when a player is trying to join due a server transfer when it is" +
            " not allowed.")
    @CustomKey("transfers-not-allowed-message")
    private @MonotonicNonNull String transfersNotAllowedMessage = createTransfersNotAllowedMessage();

    private UnparsedServerConfiguration() {}

    /**
     * Gets a message that should be used as a description of default {@linkplain ServerListPing server list ping}.
     *
     * @return the message
     * @since 1.0
     * @see ServerListPing
     */
    public @NonNull String serverListDescription() {
        if (this.serverListDescription == null)
            this.serverListDescription = createDefaultServerListDescription();
        return this.serverListDescription;
    }

    /**
     * Gets a maximum amount of players, which can be on the server at once.
     *
     * <p>Note that this value by default is used only for server list pinging.</p>
     *
     * @return the amount
     * @since 1.0
     * @see ServerListPing
     */
    public int maximumPlayers() {
        return this.maxPlayers;
    }

    /**
     * Gets an address that the server should bind to.
     *
     * @return the address
     * @since 1.0
     */
    public @NonNull String address() {
        if (this.address == null)
            this.address = defaultAddress();
        return this.address;
    }

    /**
     * Gets a port that the server should bind to.
     *
     * @return the port
     * @since 1.0
     */
    public int port() {
        return this.port;
    }

    /**
     * Gets a packet length, since which packets should be compressed.
     *
     * @return the packet length
     * @since 1.0
     */
    public int compressionThreshold() {
        return this.compressionThreshold;
    }

    /**
     * Gets {@linkplain NettyTransportSelector a netty transport selector} that the server should use for selecting
     * netty native transport.
     *
     * @return the netty transport selector
     * @since 1.0
     */
    public @NonNull NettyTransportSelector transportSelector() {
        if (this.transport == null)
            this.transport = NettyTransportSelector.AUTO;
        return this.transport;
    }

    /**
     * Gets a message used during disconnection when a player is trying to join with an unsupported version.
     *
     * @return the message
     * @since 1.0
     */
    public @NonNull String unsupportedVersionMessage() {
        if (this.unsupportedVersionMessage == null)
            this.unsupportedVersionMessage = createDefaultUnsupportedVersionMessage();
        return this.unsupportedVersionMessage;
    }

    /**
     * Gets {@linkplain Set a set} of {@linkplain Key keys} of {@linkplain FeaturePack feature packs} that should
     * be enabled on the server.
     *
     * @return the set
     * @since 1.0
     */
    public @NonNull Set<Key> enabledFeaturePacks() {
        if (this.enabledFeaturePacks == null)
            this.enabledFeaturePacks = createDefaultEnabledFeaturePacks();

        if (!this.enabledFeaturePacks.contains(FeaturePacks.CORE)) {
            Set<Key> enabledPacks = new HashSet<>(this.enabledFeaturePacks);
            enabledPacks.add(FeaturePacks.CORE);
            this.enabledFeaturePacks = Set.copyOf(enabledPacks);
        }

        return Set.copyOf(this.enabledFeaturePacks);
    }

    /**
     * Gets whether clients joining due a server transfer are allowed.
     *
     * @return {@code true} if the clients joining due a server transfer are allowed, {@code false} otherwise
     * @since 1.0
     */
    public boolean areTransfersAllowed() {
        return this.transfersAllowed;
    }

    /**
     * Gets a message used during disconnection when a player is trying to join due a server transfer when it is not
     * allowed.
     *
     * @return the message
     * @since 1.0
     */
    public @NonNull String transfersNotAllowedMessage() {
        if (this.transfersNotAllowedMessage == null)
            this.transfersNotAllowedMessage = createTransfersNotAllowedMessage();
        return this.transfersNotAllowedMessage;
    }

    /**
     * Creates and loads {@linkplain UnparsedServerConfiguration an unparsed server configuration}.
     *
     * @return the unparsed server configuration
     * @since 1.0
     */
    public static @NonNull UnparsedServerConfiguration create() {
        UnparsedServerConfiguration configuration = new UnparsedServerConfiguration();

        configuration.withBindFile(Path.of("server.yaml"));
        configuration.withConfigurer(new YamlSnakeYamlConfigurer(), new UnparsedConfigurationSerdes());
        configuration.withRemoveOrphans(true);
        configuration.saveDefaults();
        configuration.load(true);

        return configuration;
    }

    private static @NonNull String createDefaultUnsupportedVersionMessage() {
        return String.format(
                "<dark_red><bold>Unsupported version! Please use <%s>.</bold></dark_red>",
                ConfigurationPlaceholder.MINECRAFT_VERSION_NAME.placeholderName()
        );
    }

    private static @NonNull String createDefaultServerListDescription() {
        return "<dark_purple>A Jet server</dark_purple>";
    }

    private static @NonNull String defaultAddress() {
        return "0.0.0.0";
    }

    private static @NonNull Set<Key> createDefaultEnabledFeaturePacks() {
        return Set.of(FeaturePacks.CORE);
    }

    private static @NonNull String createTransfersNotAllowedMessage() {
        return "<red>Transfers are not allowed on this server!</red>";
    }
}