package net.hypejet.jet.server.registry;

import com.google.common.primitives.ImmutableIntArray;
import net.hypejet.jet.data.autogenerated.server.ResourceFileNames;
import net.hypejet.jet.data.codecs.JetDataJson;
import net.hypejet.jet.data.model.api.block.entity.BlockEntityType;
import net.hypejet.jet.data.model.api.registries.armor.material.ArmorTrimMaterial;
import net.hypejet.jet.data.model.api.registries.armor.pattern.ArmorTrimPattern;
import net.hypejet.jet.data.model.api.registries.banner.BannerPattern;
import net.hypejet.jet.data.model.api.registries.biome.Biome;
import net.hypejet.jet.data.model.api.registries.chat.ChatType;
import net.hypejet.jet.data.model.api.registries.damage.DamageType;
import net.hypejet.jet.data.model.api.registries.dimension.DimensionType;
import net.hypejet.jet.data.model.api.registries.painting.PaintingVariant;
import net.hypejet.jet.data.model.api.registries.wolf.WolfVariant;
import net.hypejet.jet.data.model.server.registry.registries.block.Block;
import net.hypejet.jet.data.model.server.registry.registries.block.state.BlockState;
import net.hypejet.jet.data.model.server.registry.registries.pack.FeaturePack;
import net.hypejet.jet.data.model.server.registry.registries.registry.DataRegistryEntry;
import net.hypejet.jet.registry.RegistryManager;
import net.hypejet.jet.server.JetMinecraftServer;
import net.hypejet.jet.server.registry.tags.Tags;
import net.hypejet.jet.server.registry.writers.registry.armor.material.ArmorTrimMaterialBinaryTagWriter;
import net.hypejet.jet.server.registry.writers.registry.armor.pattern.ArmorTrimPatternBinaryTagWriter;
import net.hypejet.jet.server.registry.writers.registry.banner.BannerPatternBinaryTagWriter;
import net.hypejet.jet.server.registry.writers.registry.biome.BiomeBinaryTagWriter;
import net.hypejet.jet.server.registry.writers.registry.chat.ChatTypeBinaryTagWriter;
import net.hypejet.jet.server.registry.writers.registry.damage.DamageTypeBinaryTagWriter;
import net.hypejet.jet.server.registry.writers.registry.dimension.DimensionTypeBinaryTagWriter;
import net.hypejet.jet.server.registry.writers.registry.painting.PaintingVariantBinaryTagWriter;
import net.hypejet.jet.server.registry.writers.registry.wolf.WolfVariantBinaryTagWriter;
import net.hypejet.jet.server.util.order.ElementOrder;
import net.hypejet.jet.server.world.block.BlockType;
import net.kyori.adventure.key.Key;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Represents an implementation of {@linkplain RegistryManager a registry manager}.
 *
 * @since 1.0
 * @see RegistryManager
 */
public final class JetRegistryManager implements RegistryManager {

    private final Set<JetMinecraftRegistry<?>> registries;
    private final Set<FeaturePack> enabledFeaturePacks;

    private final JetSerializableMinecraftRegistry<DimensionType> dimensionTypeRegistry;
    private final JetSerializableMinecraftRegistry<ChatType> chatTypeRegistry;
    private final JetSerializableMinecraftRegistry<DamageType> damageTypeRegistry;
    private final JetSerializableMinecraftRegistry<BannerPattern> bannerPatternRegistry;
    private final JetSerializableMinecraftRegistry<WolfVariant> wolfVariantRegistry;
    private final JetSerializableMinecraftRegistry<Biome> biomeRegistry;
    private final JetSerializableMinecraftRegistry<PaintingVariant> paintingVariantRegistry;
    private final JetSerializableMinecraftRegistry<ArmorTrimMaterial> armorTrimMaterialRegistry;
    private final JetSerializableMinecraftRegistry<ArmorTrimPattern> armorTrimPatternRegistry;

    private final JetMinecraftRegistry<BlockEntityType> blockEntityTypeRegistry;
    private final JetMinecraftRegistry<BlockType> blockTypeRegistry;

    private final ElementOrder<BlockState> blockStateOrder;

    /**
     * Constructs the {@linkplain JetRegistryManager registry manager}.
     *
     * @param server a server, for which the registries should be managed
     * @since 1.0
     */
    public JetRegistryManager(@NonNull JetMinecraftServer server) {
        List<DataRegistryEntry<?>> featurePackEntries = JetMinecraftRegistry.entries(
                JetDataJson.createPlainGson(),
                ResourceFileNames.FEATURE_PACK_GENERATOR
        );

        Logger logger = LoggerFactory.getLogger(JetRegistryManager.class);
        Set<FeaturePack> enabledFeaturePacks = new HashSet<>();

        for (Key packKey : server.configuration().enabledFeaturePacks()) {
            FeaturePack featurePack = null;

            for (DataRegistryEntry<?> featurePackEntry : featurePackEntries) {
                if (!featurePackEntry.key().equals(packKey)) continue;

                Object value = featurePackEntry.value();
                if (!FeaturePack.class.isAssignableFrom(value.getClass()))
                    throw new IllegalArgumentException("A feature pack clas is not assignable from the entry value");
                featurePack = (FeaturePack) value;
            }

            if (featurePack == null) {
                logger.warn("Could not find a feature pack with key of \"{}\", skipping...", packKey);
                continue;
            }

            enabledFeaturePacks.add(featurePack);
            logger.info("Enabled feature pack with key of \"{}\"", packKey);
        }

        this.enabledFeaturePacks = Set.copyOf(enabledFeaturePacks);

        this.dimensionTypeRegistry = JetSerializableMinecraftRegistry.create(
                Key.key("dimension_type"), DimensionType.class, server,
                DimensionTypeBinaryTagWriter.INSTANCE, this.enabledFeaturePacks,
                JetDataJson.createDimensionTypesGson(), ResourceFileNames.DIMENSION_TYPE_GENERATOR
        );

        this.chatTypeRegistry = JetSerializableMinecraftRegistry.create(
                Key.key("chat_type"), ChatType.class, server, ChatTypeBinaryTagWriter.INSTANCE,
                this.enabledFeaturePacks, JetDataJson.createChatTypesGson(),
                ResourceFileNames.CHAT_TYPE_GENERATOR
        );

        this.damageTypeRegistry = JetSerializableMinecraftRegistry.create(
                Key.key("damage_type"), DamageType.class, server, DamageTypeBinaryTagWriter.INSTANCE,
                this.enabledFeaturePacks, JetDataJson.createDamageTypesGson(),
                ResourceFileNames.DAMAGE_TYPE_GENERATOR
        );

        this.bannerPatternRegistry = JetSerializableMinecraftRegistry.create(
                Key.key("banner_pattern"), BannerPattern.class, server,
                BannerPatternBinaryTagWriter.INSTANCE, this.enabledFeaturePacks,
                JetDataJson.createBannerPatternsGson(), ResourceFileNames.BANNER_PATTERN_GENERATOR
        );

        this.wolfVariantRegistry = JetSerializableMinecraftRegistry.create(
                Key.key("wolf_variant"), WolfVariant.class, server, WolfVariantBinaryTagWriter.INSTANCE,
                this.enabledFeaturePacks, JetDataJson.createWolfVariantsGson(),
                ResourceFileNames.WOLF_VARIANT_GENERATOR
        );

        this.biomeRegistry = JetSerializableMinecraftRegistry.create(
                Key.key("worldgen/biome"), Biome.class, server, BiomeBinaryTagWriter.INSTANCE,
                this.enabledFeaturePacks, JetDataJson.createBiomesGson(), ResourceFileNames.BIOME_GENERATOR
        );

        this.paintingVariantRegistry = JetSerializableMinecraftRegistry.create(
                Key.key("painting_variant"), PaintingVariant.class, server,
                PaintingVariantBinaryTagWriter.INSTANCE, this.enabledFeaturePacks,
                JetDataJson.createPaintingVariantsGson(), ResourceFileNames.PAINTING_VARIANT_GENERATOR
        );

        this.armorTrimMaterialRegistry = JetSerializableMinecraftRegistry.create(
                Key.key("trim_material"), ArmorTrimMaterial.class, server,
                ArmorTrimMaterialBinaryTagWriter.INSTANCE, this.enabledFeaturePacks,
                JetDataJson.createTrimMaterialsGson(), ResourceFileNames.ARMOR_TRIM_MATERIAL_GENERATOR
        );

        this.armorTrimPatternRegistry = JetSerializableMinecraftRegistry.create(
                Key.key("trim_pattern"), ArmorTrimPattern.class, server,
                ArmorTrimPatternBinaryTagWriter.INSTANCE, this.enabledFeaturePacks,
                JetDataJson.createTrimPatternsGson(), ResourceFileNames.ARMOR_TRIM_PATTERN_GENERATOR
        );

        this.blockEntityTypeRegistry = JetMinecraftRegistry.create(
                Key.key("block-entity-types"), BlockEntityType.class, server,
                enabledFeaturePacks, JetDataJson.createBlockEntityTypeGson(),
                ResourceFileNames.BLOCK_ENTITY_TYPE_GENERATOR
        );

        this.blockStateOrder = createBlockStateOrder();
        this.blockTypeRegistry = createBlockTypeRegistry(this.blockStateOrder, server, enabledFeaturePacks);

        this.registries = Set.of(
                // TODO: Add block, item, fluid and game event registries
                this.dimensionTypeRegistry, this.chatTypeRegistry, this.damageTypeRegistry, this.bannerPatternRegistry,
                this.wolfVariantRegistry, this.biomeRegistry, this.paintingVariantRegistry,
                this.armorTrimMaterialRegistry, this.armorTrimPatternRegistry
        );
    }

    @Override
    public @NonNull JetSerializableMinecraftRegistry<DimensionType> dimensionTypeRegistry() {
        return this.dimensionTypeRegistry;
    }

    @Override
    public @NonNull JetSerializableMinecraftRegistry<ChatType> chatTypeRegistry() {
        return this.chatTypeRegistry;
    }

    @Override
    public @NonNull JetSerializableMinecraftRegistry<DamageType> damageTypeRegistry() {
        return this.damageTypeRegistry;
    }

    @Override
    public @NonNull JetSerializableMinecraftRegistry<BannerPattern> bannerPatternRegistry() {
        return this.bannerPatternRegistry;
    }

    @Override
    public @NonNull JetSerializableMinecraftRegistry<WolfVariant> wolfVariantRegistry() {
        return this.wolfVariantRegistry;
    }

    @Override
    public @NonNull JetSerializableMinecraftRegistry<Biome> biomeRegistry() {
        return this.biomeRegistry;
    }

    @Override
    public @NonNull JetSerializableMinecraftRegistry<PaintingVariant> paintingVariantRegistry() {
        return this.paintingVariantRegistry;
    }

    @Override
    public @NonNull JetSerializableMinecraftRegistry<ArmorTrimMaterial> trimMaterialRegistry() {
        return this.armorTrimMaterialRegistry;
    }

    @Override
    public @NonNull JetSerializableMinecraftRegistry<ArmorTrimPattern> trimPatternRegistry() {
        return this.armorTrimPatternRegistry;
    }

    @Override
    public @NonNull JetMinecraftRegistry<BlockType> blockTypeRegistry() {
        return this.blockTypeRegistry;
    }

    @Override
    public @NonNull JetMinecraftRegistry<BlockEntityType> blockEntityTypeRegistry() {
        return this.blockEntityTypeRegistry;
    }

    /**
     * Gets {@linkplain Set a set} of all registries of this {@linkplain JetRegistryManager registry manager}.
     *
     * @return the set
     * @since 1.0
     */
    public @NonNull Set<JetMinecraftRegistry<?>> registries() {
        return this.registries;
    }

    /**
     * Gets {@linkplain Set a set} of enabled {@linkplain FeaturePack feature packs}.
     *
     * @return the set
     * @since 1.0
     */
    public @NonNull Set<FeaturePack> enabledFeaturePacks() {
        return this.enabledFeaturePacks;
    }

    /**
     * Gets {@linkplain ElementOrder an element order} of {@linkplain BlockState block states}.
     *
     * @return the element order
     * @since 1.0
     */
    public @NonNull ElementOrder<BlockState> blockStateOrder() {
        return this.blockStateOrder;
    }

    private static @NonNull ElementOrder<BlockState> createBlockStateOrder() {
        List<DataRegistryEntry<?>> dataEntries = JetMinecraftRegistry.entries(
                JetDataJson.createBlockStatesGson(),
                ResourceFileNames.BLOCK_STATE_GENERATOR
        );

        List<BlockState> blockStates = new ArrayList<>();
        for (DataRegistryEntry<?> blockStateEntry : dataEntries) {
            if (!(blockStateEntry.value() instanceof BlockState blockState))
                throw new IllegalArgumentException("The value is not a block state");
            blockStates.add(blockState);
        }

        return new ElementOrder<>(blockStates);
    }

    private static @NonNull JetMinecraftRegistry<BlockType> createBlockTypeRegistry(
            @NonNull ElementOrder<BlockState> blockStateOrder,
            @NonNull JetMinecraftServer server,
            @NonNull Set<FeaturePack> enabledFeaturePacks
    ) {
        List<DataRegistryEntry<?>> dataEntries = JetMinecraftRegistry.entries(
                JetDataJson.createBlocksGson(),
                ResourceFileNames.BLOCK_GENERATOR
        );

        List<JetRegistryEntry<BlockType>> blockTypeEntries = new ArrayList<>();
        Map<JetRegistryEntry<BlockType>, Tags> blockTypeEntryToTagsMap = new HashMap<>();

        for (int index = 0; index < dataEntries.size(); index++) {
            DataRegistryEntry<?> dataEntry = dataEntries.get(index);
            JetRegistryEntry<BlockType> entry = createBlockTypeEntry(blockStateOrder, dataEntry);

            Collection<Key> tagsCollection = dataEntry.tags();
            if (tagsCollection == null)
                tagsCollection = Set.of();

            blockTypeEntries.add(index, entry);
            blockTypeEntryToTagsMap.put(entry, new Tags(tagsCollection));
        }

        return new JetMinecraftRegistry<>(
                Key.key("blocks"), BlockType.class, server,
                blockTypeEntries, enabledFeaturePacks, blockTypeEntryToTagsMap
        );
    }

    private static @NonNull JetRegistryEntry<BlockType> createBlockTypeEntry(
            @NonNull ElementOrder<BlockState> blockStateOrder,
            @NonNull DataRegistryEntry<?> dataEntry
    ) {
        if (!(dataEntry.value() instanceof Block(
                Set<Key> requiredFeatureFlags, int defaultBlockStateId,
                ImmutableIntArray possibleBlockStateIdentifiers
        ))) {
            throw new IllegalArgumentException("The value is not a block");
        }

        BlockState blockState = blockStateOrder.getOrThrow(defaultBlockStateId);
        Set<BlockState> possibleBlockStates = new HashSet<>();

        for (int identifier : possibleBlockStateIdentifiers.toArray())
            possibleBlockStates.add(blockStateOrder.getOrThrow(identifier));

        return new JetRegistryEntry<>(
                dataEntry.key(),
                new BlockType(blockState, requiredFeatureFlags, possibleBlockStates),
                null
        );
    }
}